### ISSUE TITLE
Eagle Console - Set up Mock server using contract with backend

### ISSUE THREAD

**Issue by sandyasheri-gft** [tranquilitybase-io/tb-gcp#106]
Setup localhost service that will return REST calls with dummy data

**Comment by sandyasheri-gft** [comment]
- [ ] Create back end services for activators (applications) 

- [ ] Create back end services for solutions pages

**Comment by oscarmon7** [comment]
Mock server developed in repo _tb-eagle-console_ and deployed in EC already.
