### ISSUE TITLE
Get rid of deprecation warnings in LZ deployment

### ISSUE THREAD

**Issue by oscarmon7** [tranquilitybase-io/tb-gcp#137]
Several deprecation warnings are displayed along the LZ process. They should be remediated.

Warning: google_project_services is deprecated - many users reported issues with dependent services that were not resolvable.  Please use google_project_service or the https://github.com/terraform-google-modules/terraform-google-project-factory/tree/master/modules/project_services module.  It's recommended that you use a provider version of 2.13.0 or higher when you migrate so that requests are batched to the API, reducing the request rate. This resource will be removed in version 3.0.0.
  on ../../apis-activation/main.tf line 15, in resource "google_project_services" "project":
  15: resource "google_project_services" "project" {

Warning: google_project_services is deprecated - many users reported issues with dependent services that were not resolvable.  Please use google_project_service or the https://github.com/terraform-google-modules/terraform-google-project-factory/tree/master/modules/project_services module.  It's recommended that you use a provider version of 2.13.0 or higher when you migrate so that requests are batched to the API, reducing the request rate. This resource will be removed in version 3.0.0.
  on ../../apis-activation/main.tf line 54, in resource "google_project_services" "project_shared":
  54: resource "google_project_services" "project_shared" {

Warning: "region": [DEPRECATED] Use location instead
  on ../../kubernetes-cluster-creation/gke.tf line 15, in resource "google_container_cluster" "gke":
  15: resource "google_container_cluster" "gke" {

Warning: "region": [DEPRECATED] Use location instead
  on ../../kubernetes-cluster-creation/gke.tf line 15, in resource "google_container_cluster" "gke":
  15: resource "google_container_cluster" "gke" {

Warning: "region": [DEPRECATED] Use location instead
  on ../../kubernetes-cluster-creation/gke.tf line 15, in resource "google_container_cluster" "gke":
  15: resource "google_container_cluster" "gke" {

Warning: "region": [DEPRECATED] use location instead
  on ../../kubernetes-cluster-creation/gke.tf line 91, in resource "google_container_node_pool" "gke_node_pool":
  91: resource "google_container_node_pool" "gke_node_pool" {

Warning: "region": [DEPRECATED] use location instead
  on ../../kubernetes-cluster-creation/gke.tf line 91, in resource "google_container_node_pool" "gke_node_pool":
  91: resource "google_container_node_pool" "gke_node_pool" {
  
Warning: "region": [DEPRECATED] use location instead
  on ../../kubernetes-cluster-creation/gke.tf line 91, in resource "google_container_node_pool" "gke_node_pool":
  91: resource "google_container_node_pool" "gke_node_pool" {

Warning: "enable_flow_logs": [DEPRECATED] This field is being removed in favor of log_config. If log_config is present, flow logs are enabled.
  on ../../shared-vpc/main.tf line 34, in resource "google_compute_subnetwork" "standard":
  34: resource "google_compute_subnetwork" "standard" {

Warning: "enable_flow_logs": [DEPRECATED] This field is being removed in favor of log_config. If log_config is present, flow logs are enabled.
  on ../../shared-vpc/main.tf line 47, in resource "google_compute_subnetwork" "gke":
  47: resource "google_compute_subnetwork" "gke" {

Warning: "enable_flow_logs": [DEPRECATED] This field is being removed in favor of log_config. If log_config is present, flow logs are enabled.
  on ../../shared-vpc/main.tf line 72, in resource "google_compute_subnetwork" "tb-bastion-subnetwork":
  72: resource "google_compute_subnetwork" "tb-bastion-subnetwork" {

**Comment by RDHA-GFT** [comment]
Here is the summary list of warnings and errors

https://tranquilitybasegroup.slack.com/files/U01144SLBEU/F013S8WF188/issue_137_warnings.xlsx?origin_team=TL4BM9CDQ&origin_channel=C0116TQC1CK

**Comment by RDHA-GFT** [comment]
New code for **google_project_service**
https://www.terraform.io/docs/providers/google/guides/version_3_upgrade.html#resource-google_project_services

**Comment by RDHA-GFT** [comment]
https://www.terraform.io/docs/providers/google/guides/version_3_upgrade.html#resource-google_compute_subnetwork

**Comment by connor-mcshane** [comment]
**On hold until #292 and #291 are finished**
