### ISSUE TITLE
Modularise Landing Zone deployment

### ISSUE THREAD

**Issue by oscarmon7** [tranquilitybase-io/tb-gcp#138]
Explore modularisation of Landing Zone deployment with terragrunt

**Comment by oscarmon7** [comment]
Initial design does not involve terragrunt. We are going to create the following structure with additional states for each one of the optional modules:

- Basic landing zone will continue to use the same state            --> state /landingzone
	- Folder structure (Applications and Shared services)
	- Create Shared services projects
	- Created a shared VPC
	- Create K8s SSP cluster
	- Create “ssp-activator-tf” cloud source repo to store activator code
	- Deploy SSP Portal (App Engine)
	- Create “terraform-code-store” cloud source repo
	- Deploy the two bastion hosts
- Security (folder to be renamed secrets per #148)
	- main.tf - Create k8s Security cluster                       --> state /secrets
	- vault
	        -main.tf – Deploy vault inside K8S security cluster    --> state /secrets/vault
	- option2
	        - main.tf – Deploy secrets 2nd option                    --> state /secrets/option2
	- option3
	        - main.tf – Deploy secrets 3rd option                   --> state /secrets/option3
- Operations (folder to renamed itsm per #147)
	- main.tf - Create k8s operations cluster                     --> state /itsm
	- itop
	        - main.tf – Deploy iTop inside K8S operatoins cluster   --> state /itsm/itop
	- option2
	        - main.tf – Deploy secrets 2nd option                    --> state /itsm/option2
	- option3
	        - main.tf – Deploy secrets 3rd option                   --> state /itsm/option3

**Comment by oscarmon7** [comment]
Split into #223 and #224

**Comment by andy12838729** [comment]
iTop should be part of the later install in the Datacentre - once the LZ has been built. It should be invoked from the Eagle Console.
