### ISSUE TITLE
Deployment failure out of europe-west2 region

### ISSUE THREAD

**Issue by oscarmon7** [tranquilitybase-io/tb-gcp#145]
Deployment of LZ fails with the following error when a zone out of the europe-west2 region is selected. (Error re-created in: europe-west3-a, us-east1-b, us-east4-a and asia-south1-c; successful deployment achieved in europe-west2-a and europe-west2-c.)

_Error: Error retrieving IAM policy for compute subnetwork "projects/shared-networking-a4e11ef9/regions/us-east1/subnetworks/bastion-subnetwork": googleapi: Error 404: The resource 'projects/shared-networking-a4e11ef9/regions/us-east1/subnetworks/bastion-subnetwork' was not found, notFound
  on ../../bastion/main.tf line 14, in resource "google_compute_subnetwork_iam_binding" "bastion_subnet_permission":
  14: resource "google_compute_subnetwork_iam_binding" "bastion_subnet_permission" {
Error: Error retrieving IAM policy for compute subnetwork "projects/shared-networking-a4e11ef9/regions/us-east1/subnetworks/shared-operations-snet": googleapi: Error 404: The resource 'projects/shared-networking-a4e11ef9/regions/us-east1/subnetworks/shared-operations-snet' was not found, notFound
  on ../../kubernetes-cluster-creation/iam.tf line 68, in resource "google_compute_subnetwork_iam_member" "cluster_networkUser_1":
  68: resource "google_compute_subnetwork_iam_member" "cluster_networkUser_1" {
Error: Error retrieving IAM policy for compute subnetwork "projects/shared-networking-a4e11ef9/regions/us-east1/subnetworks/shared-ssp-snet": googleapi: Error 404: The resource 'projects/shared-networking-a4e11ef9/regions/us-east1/subnetworks/shared-ssp-snet' was not found, notFound
  on ../../kubernetes-cluster-creation/iam.tf line 68, in resource "google_compute_subnetwork_iam_member" "cluster_networkUser_1":
  68: resource "google_compute_subnetwork_iam_member" "cluster_networkUser_1" {
Error: Error retrieving IAM policy for compute subnetwork "projects/shared-networking-a4e11ef9/regions/us-east1/subnetworks/shared-security-snet": googleapi: Error 404: The resource 'projects/shared-networking-a4e11ef9/regions/us-east1/subnetworks/shared-security-snet' was not found, notFound
  on ../../kubernetes-cluster-creation/iam.tf line 68, in resource "google_compute_subnetwork_iam_member" "cluster_networkUser_1":
  68: resource "google_compute_subnetwork_iam_member" "cluster_networkUser_1" {
Error: Error retrieving IAM policy for compute subnetwork "projects/shared-networking-a4e11ef9/regions/us-east1/subnetworks/shared-ssp-snet": googleapi: Error 404: The resource 'projects/shared-networking-a4e11ef9/regions/us-east1/subnetworks/shared-ssp-snet' was not found, notFound
  on ../../kubernetes-cluster-creation/iam.tf line 79, in resource "google_compute_subnetwork_iam_member" "cluster_networkUser_2":
  79: resource "google_compute_subnetwork_iam_member" "cluster_networkUser_2" {
Error: Error retrieving IAM policy for compute subnetwork "projects/shared-networking-a4e11ef9/regions/us-east1/subnetworks/shared-security-snet": googleapi: Error 404: The resource 'projects/shared-networking-a4e11ef9/regions/us-east1/subnetworks/shared-security-snet' was not found, notFound
  on ../../kubernetes-cluster-creation/iam.tf line 79, in resource "google_compute_subnetwork_iam_member" "cluster_networkUser_2":
  79: resource "google_compute_subnetwork_iam_member" "cluster_networkUser_2" {
Error: Error retrieving IAM policy for compute subnetwork "projects/shared-networking-a4e11ef9/regions/us-east1/subnetworks/shared-operations-snet": googleapi: Error 404: The resource 'projects/shared-networking-a4e11ef9/regions/us-east1/subnetworks/shared-operations-snet' was not found, notFound
  on ../../kubernetes-cluster-creation/iam.tf line 79, in resource "google_compute_subnetwork_iam_member" "cluster_networkUser_2":
  79: resource "google_compute_subnetwork_iam_member" "cluster_networkUser_2" {
Error: Error creating RouterNat: googleapi: Error 400: Invalid value for field 'resource.nats[0].natIps[0]': 'projects/shared-networking-a4e11ef9/regions/us-east1/addresses/nat-static-ip'. Can not use Nat IPs that do not belong to the same region., invalid
  on ../../shared-vpc/main.tf line 97, in resource "google_compute_router_nat" "simple-nat":
  97: resource "google_compute_router_nat" "simple-nat" {_

**Comment by sunderhill-gft** [comment]
After removing default values for 'europe-west2' and correcting any resulting errors the deployment does work for other regions. It doesn't work for regions which don't support 'App Engine' - see #157 
Works: asia-northeast2-b
Doesn't work: us-west3
