### ISSUE TITLE
Rename security to secrets

### ISSUE THREAD

**Issue by oscarmon7** [tranquilitybase-io/tb-gcp#148]
Rename security to secrets

**Comment by connor-mcshane** [comment]
@oscarmon7  just double-checking, this is renaming the "shared-security" project to -> "shared-secrets" ?

**Comment by oscarmon7** [comment]
Yes, that's right. Also, anything that relates to the security project needs renaming. E.g., "module.gke-security.cluster_endpoint" --> "module.gke-secrets.cluster_endpoint"
