### ISSUE TITLE
Terraform destroy doesn't destroy all LZ

### ISSUE THREAD

**Issue by oscarmon7** [tranquilitybase-io/tb-gcp#149]
Terraform destroy doesn't destroy all LZ

**Comment by connor-mcshane** [comment]
@scottholmangft 
This is because there is a lien on the VPC host project (shared networking).

```
This lien is added to prevent the deletion of this shared VPC host project. 
This project should be disabled as a shared VPC host before it is deleted, 
otherwise, it can cause networking outages in attached service projects.
```

Should this ticket be closed as wont do?

**Comment by zi01farm** [comment]
As per https://cloud.google.com/vpc/docs/deprovisioning-shared-vpc
