### ISSUE TITLE
Exposed Username and password in URI

### ISSUE THREAD

**Issue by x1mdev** [tranquilitybase-io/tb-gcp#17]
Potential security breach. See https://github.com/tranquilitybase-io/tb-gcp/blob/master/tb-self-service-portal-ui/src/app/core/services/deploy.service.ts

Looks like your github username & password are in the file in plaintext

**Comment by rjmco** [comment]
@x1mdev Thank you for reporting this issue.

The account mentioned on the code has been deleted a few weeks back before this repository was published publicly.

As part of the publishing process we tried to remove all plaintext username and passwords from the code and adjust the Github URLs to mention the now public repository. It seems this one skipped our code review.

Once again, thank you for identifying this issue. We value and welcome similar reports.

**Comment by parmendra17** [comment]
Fixed in PR #18
