### ISSUE TITLE
Cannot create application from Tranquility Base Dashboard

### ISSUE THREAD

**Issue by sunderhill-gft** [tranquilitybase-io/tb-gcp#178]
Cannot create application from Tranquility Base Dashboard. Get the error 'There was an error during activator build' when submitting.
This error happens when submitting from the Bastion host.
The application created should currently be the Jenkins from the default activator.

**Comment by oscarmon7** [comment]
Appengine is to be decommissioned. Probably won't do this one

**Comment by oscarmon7** [comment]
Appengine decommissioned already: #192
