### ISSUE TITLE
API permission changes

### ISSUE THREAD

**Issue by sunderhill-gft** [tranquilitybase-io/tb-gcp#182]
Only enable required APIs for Tranquility Base deployment.

Not required (a priori):
  - bigquery-json.googleapis.com
  - bigquerystorage.googleapis.com
  - datastore.googleapis.com
  - pubsub.googleapis.com

Check:
- cloudkms.googleapis.com
- iamcredentials.googleapis.com
- oslogin.googleapis.com 
- sqladmin.googleapis.com

**Comment by oscarmon7** [comment]
Must disable appengine too
