### ISSUE TITLE
Packer is still  building the old SSP UI

### ISSUE THREAD

**Issue by oscarmon7** [tranquilitybase-io/tb-gcp#222]
Packer is stll running the SSP UI  built which has been replaced by Eagle. This code snippet is no longer required.

_# Build self service portal ui angular app_
_cd /opt/tb/repo/tb-self-service-portal-ui/_

_sudo npm install_
_sudo npm run build --prod_

**Comment by zi01** [comment]
Code snippet no longer exists.
