### ISSUE TITLE
Optional deployment of Vault

### ISSUE THREAD

**Issue by oscarmon7** [tranquilitybase-io/tb-gcp#223]
Split of #138 - part 1.

Vault will be optional deployment  in  LZ. Refactor the code is required.
New folder _tb-gcp/tb-gcp-tr/options/secrets_ will be created with the following contents:
- main.tf - Create k8s Secrets cluster --> state with prefix /secrets
- other required files by the Secrets cluster
    - vault folder
        - main.tf – Deploy vault inside K8S security cluster --> state with prefix /secrets/vault
        - other required modules by Vault only
    - option2 (eventually)
        - main.tf – Deploy secrets 2nd option --> state with prefix /secrets/option2
    - option3 (eventually)
        - main.tf – Deploy secrets 3rd option --> state with prefix /secrets/option3

**Comment by oscarmon7** [comment]
Development is done and tested in branch _issue-223_. Deployment of the secrets cluster and Vault is working as described. However, Vault endpoint is not working so, this branch will not be merged until #225 is fixed.

**Comment by RDHA-GFT** [comment]
Will be optionally deployed via EC as separate activator
