### ISSUE TITLE
Optional deployment of itop

### ISSUE THREAD

**Issue by oscarmon7** [tranquilitybase-io/tb-gcp#224]
Split of #138 - part 2.

Itop will be optional deployment in LZ. Refactor the code is required.
New folder _tb-gcp/tb-gcp-tr/options/itsm_ will be created with the following contents:
- main.tf - Create K8s itsm cluster --> state with prefix /itsm
- other required files by the itsm cluster
    - itop folder
        - main.tf – Deploy itop inside K8S itsm cluster --> state with prefix /itsm/itop
        - other required modules by Itop only
    - option2 (eventually)
        - main.tf – Deploy itsm 2nd option --> state with prefix /itsm/option2
    - option3 (eventually)
        - main.tf – Deploy itsm 3rd option --> state with prefix /itsm/option3

**Comment by RDHA-GFT** [comment]
Will be covered by structure refresh and optional services will be deployed as separate activators.
