### ISSUE TITLE
Simplify TB deployment UI

### ISSUE THREAD

**Issue by oscarmon7** [tranquilitybase-io/tb-gcp#227]
After implementation of #221, the input fields Folder Id and Billing Account Id won't be strictly required at the TB deployment page.
- folder Id: must be picked up from the parent-id of the bootstrap project
- billing Account: must be the related Billing Account of the bootstrap project

An additional check should be implemented so that Deploy wasn't possible if the selected project is not a "bootstrap project". E.g,.:
- if project is not under a folder called "Tranquility Base*"
- if project does not contain a service account with a particular name such as "bootstrap-sa"

**Comment by RDHA-GFT** [comment]
No longer relevant
