### ISSUE TITLE
Create TB folder in config script and bootstrap project inside TB folder

### ISSUE THREAD

**Issue by connor-mcshane** [tranquilitybase-io/tb-gcp#228]
split from #221    implements part of #236

In config creator:
- Create TB folder using the discriminator (name will be "Tranquility Base - XXXXXXXX", removed "tb" to avoid redundancy)
- Create bootstrap project under the TB folder (name will be "bootstrap-XXXXXXXX"; remove "-tb" to avoid redundancy)

In TF:
- Remove the creation of the TB folder
- Use data.google_folder to get data of the TB folder
- Decomission variable "root_is_org" (it will always be folder)

Update tb-projects-deleter:
- Update README file accordingly

**Comment by connor-mcshane** [comment]
This is dev complete, just need input from @scottholmangft  to double-check.

![image](https://user-images.githubusercontent.com/10451364/78248562-c550e500-74e4-11ea-9203-1a52fb174371.png)

![image](https://user-images.githubusercontent.com/10451364/78248606-dd286900-74e4-11ea-96ad-18565bf28e27.png)

**Comment by andy12838729** [comment]
I think this may now have changed based on the latest high level arch diagram.

![High_Level_Architecture](https://user-images.githubusercontent.com/53095823/79558262-c57fe180-809b-11ea-8b84-383e2d655c74.png)
