### ISSUE TITLE
Folder Hierachy Structure

### ISSUE THREAD

**Issue by connor-mcshane** [tranquilitybase-io/tb-gcp#239]
# Folder Hierarchy

## Status

Proposed

## Context

A formalised folder structure/hierarchy is required for tranquillity base.

![image](https://user-images.githubusercontent.com/10451364/79559370-7e92eb80-809d-11ea-95d4-219357b3fd7e.png)

1. Create Datacenter as Code folder.
2. Move Bootstrap Project under Datacenter as Code folder.
3. Rename Bootstrap Project to Eagle.

## Decision

Implement the folder/project/resource hierarchy as shown in the architecture diagram.

## Consequences

-  Tf state is stored in the Eagle project, Eagle project governs the entire infrastructure configuration.
-  Need to update tb-config and terraform scripts to reflect these changes.

## Implementation or Related Issues
- #228 
- #234
- #127

**Comment by andy12838729** [comment]
I think, having reflected on this, that Eagle and the Houston service should be in the DaC folder, and the DaC container should run on the same EC cluster

**Comment by andy12838729** [comment]
Changed the diagram to the following
![High_Level_Architecture](https://user-images.githubusercontent.com/53095823/79491248-10efac80-8016-11ea-955b-5af054cef440.png)

**Comment by connor-mcshane** [comment]
@andy12838729  cool diagram,  I can update #228  to
1. Create the Datacenter as Code folder and put the bootstrap project inside the Datacenter as code folder.
2. Rename bootstrap project to Eagle project, the bootstrap vm can keep the same name.

When we get the chance we can work out the other issues that need doing and link to this diagram.

**Comment by connor-mcshane** [comment]
closed this as its not being used for discussion
