### ISSUE TITLE
[Feature] Add gcp-dac as service to Eagle Console Kubernetes Cluster

### ISSUE THREAD

**Issue by sunderhill-gft** [tranquilitybase-io/tb-gcp#255]
Add gcp-dac as service to Eagle Console Kubernetes Cluster so that solutions can be deployed on GCP

gcp-dac is an additional Docker container to add to the Cluster and should be able to communicate directly with the houston-service.

Additionally. the following configuration settings need to passed into the Eagle Console Kubernetes cluster.

* tb-discriminator - the randomly generated suffix that is added to all resources created in the landing zone. This discriminator should be used in the applications created too.
* applications-folder-id - the folder id of the applications folder created in the landing zone

To  be decided if these are added ec-config.yaml or just passed as parameters to the container.

See issues [16](https://github.com/tranquilitybase-io/tb-gcp-dac/issues/16) and   [22](https://github.com/tranquilitybase-io/tb-gcp-dac/issues/22) in the [tb-gcp-dac repo](https://github.com/tranquilitybase-io/tb-gcp-dac)

**Comment by andy12838729** [comment]
As discussed for a future upgrade, those config settings will be retrieved from the DaC database - along with others.

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/TranquilityBase/issues/14

**Comment by Salles-FA** [comment]
Hi @sunderhill-gft,

I've just tagged the latest 'integration' build with 'landingzone' to follow the same Eagle and HS tag for the images in [this cluster](https://github.com/tranquilitybase-io/tb-gcp/blob/master/tb-gcp-tr/landingZone/eagle_console.yaml), ok?
- gcr.io/tranquility-base-images/tb-eagle-console:landingzone
- gcr.io/tranquility-base-images/tb-houston-service:landingzone
- gcr.io/tranquility-base-images/tb-houston-mysql57:landingzone

And now:
- gcr.io/tranquility-base-images/tb-gcp-dac:landingzone

**Comment by connor-mcshane** [comment]
The latest changes on Master fix the eagle_console.yaml file.  Please merge master on this branch before doing any work.

Also spoke with @sunderhill-gft  and @Salles-FA. Goal of this task is to have a landing zone deployment, with all working services which the Houston team can test on.

**Comment by RDHA-GFT** [comment]
The Eagle Console should be deployed as a separate configuration to the shared GKE cluster.
The DaC and other CI\CD deployment services need be deployed as separate configuration but onto the same shared GKE cluster as EC.
The shared GKE cluster needs to be deployed as part of the core LZ configuration.

**Comment by bimalgrewal** [comment]
I created a `Deployment` and `Service` workload for DaC in the `eagle_console.yaml`, please check `issue-255` branch.

Feel free to make changes in that branch.

**Comment by arvindclement** [comment]
Had  review of the eagle console cluster we would need to create separate namespace to house the 
•	tb-eagle-console
•	tb-houston-service
•	tb-houston-mysql57
•	tb-gcp-dac:landingzone
going to create a separate ticket so that we create one for Jenkins as well. Also we need to look at renaming this EC GKE cluster to a more general name as it would have more services

**Comment by arvindclement** [comment]
This will follow once we finish #329 the reason being the DAC will need to go into a defined namespace in the shared GKE cluster either with the eagle console and houston service or on the namespace which has jenkins. Issue 329 will give us the namespaces that we would then use to put in dac

**Comment by arvindclement** [comment]
going to put this on hold until we finish #329

**Comment by sunderhill-gft** [comment]
Kubernetes config working in tb-gcp branch issue-255a.

**Comment by arvindclement** [comment]
Going to create a new PR with details from the demo we did yesterday that has all the patches that are required for eagle console, houston service and dac to work together
