### ISSUE TITLE
Review and Finalise the Shared Devops Approach Architecture for TB

### ISSUE THREAD

**Issue by arvindclement** [tranquilitybase-io/tb-gcp#266]
Review and finalise the Shared DevOps approach architecture based on the details mentioned in this issue
https://github.com/tranquilitybase-io/tb-gcp-dac/issues/27

Defintion of Done:
1.) Come up with a GitOps approach for deploying an solution/activator
2.) Define tasks required to implement the Architecture

**Comment by arvindclement** [comment]
Based on the discussion on the call with Parmendra yesterday evening discussing about  https://github.com/tranquilitybase-io/tb-gcp-dac/issues/27 will come up with a diagram explaining the flow as to where gitops fits

**Comment by arvindclement** [comment]
working on finalising the gitops for the solutions/activator workflow and as I dive deeper I am finding more and more loose ends which I am hoping to clarify and have a first draft soon.

**Comment by arvindclement** [comment]
Had a discussion with Andrew and realised that the approach needs to be reworked. Going to go through a deploy to better understand so so will put the ticked on hold until then.

**Comment by arvindclement** [comment]
As an MVP the following tasks have been ironed out and would be worked on 

1.)	Create the jenkins K8 cluster as part of the Landing zone code 
2.)	Review/Document the manual deployment of activator
https://github.com/tranquilitybase-io/tb-activator-gft-base
3.)	Spin up a Jenkins VM on GCP to understand Jenkins Configuration/plugins required
4.)	Define pipeline specifications to do Activator Deploys
5.)	Evaluate having the eagle console output artifacts for solutions/activators into a code repository
6.)	Build the Pipelines for Activator Deployments
7.)	Evaluate if we could use this shared devops approach to do CI/CD for the landing zone

**Comment by arvindclement** [comment]
I shall come up with the GitOps approach for the solution/activator and share with team but have put this ticket in the backlog until we finish the MVP tasks first

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/TranquilityBase/issues/14

**Comment by arvindclement** [comment]
Attached is the diagram for the Activator GitOps approach
[Tranquility Base-Activator-GitOps-ApproachV1.pptx](https://github.com/tranquilitybase-io/tb-gcp/files/4665122/Tranquility.Base-Activator-GitOps-ApproachV1.pptx)

Shall close this ticket and open a new one when modifications are needed on this diagram
