### ISSUE TITLE
Make Tbase services IPs internal and use Bastion Hostand IAP proxy for access

### ISSUE THREAD

**Issue by parmendra17** [tranquilitybase-io/tb-gcp#27]
Currently there are following services on Tranquility base that are accessible through external IPs: 
1. Self Service/Eagle Console website
2. Self Service Portal Backend APis
3. ITop
4. Vault
5. Jenkins for Microservices Activator

These IPs need to be made internal and exposed through a Bastion Host . The bastion host would be accessible through an IAP proxy.

**Comment by segsik-gft** [comment]
I have created a feature branch (feature/bastion-security) to apply changes, see below for progress made and what the next step is. 

- Bastion project created.
- Bastion Subnet created on shared vpc
- Bastion project attached to bastion subnet on shared VPC
- Bastion service account (For FW rule created)
- FW rule for 0.0.0.0/0 traffic modified to allow traffic from service account
- Bastion windows box created. 

ToDo

- Cleanup code and add comments
- Create IAP access to windows bastion box
- Modify kubernetes yaml deployment file to create and use internal service loadbalancers and remove external facing loadbalancer config

**Comment by scottholmangft** [comment]
There is overlap with 
Duplicate of #37
