### ISSUE TITLE
Spin up a Jenkins VM on GCP to understand Jenkins Configuration/plugins required

### ISSUE THREAD

**Issue by wills-gft** [tranquilitybase-io/tb-gcp#278]

**Comment by wills-gft** [comment]
Built out a new Docker image for a Jenkins master which now includes the following plugins:
jackson2-api
apache-httpcomponents-client-4-api
authentication-tokens
aws-credentials
aws-java-sdk
structs
trilead-api
command-launcher
credentials-binding
bouncycastle-api
google-oauth-plugin
handlebars
momentjs
pubsub-light 
kubernetes-client-api
kubernetes-credentials
slack
amazon-ecs
amazon-ecr
ace-editor
ant
antisamy-markup-formatter
jsch
display-url-api
lockable-resources
structs
branch-api
cloudbees-folder
credentials
cvs
docker-commons
docker-workflow
durable-task
external-monitor-job
icon-shim 
oauth-credentials 
htmlpublisher
handy-uri-templates-2-api
hashicorp-vault-plugin
git-client
git-server
git
github-api
github-branch-source
github
github-issues
github-oauth
github-organization-folder
github-pullrequest
github-pr-coverage-status
gitlab-merge-request-jenkins
gitlab-oauth
gitlab-plugin
google-login
google-compute-engine
google-storage-plugin
google-kubernetes-engine
google-play-android-publisher
google-cloudbuild
google-source-plugin
google-chat-notification
googleanalytics
google-git-notes-publisher
google-metadata-plugin
google-container-registry-auth
google-cloud-backup
googlecode
google-cloud-health-check
google-deployment-manager
google-chat-notification
#google-container-security-plugin
google-admin-sdk
gradle
javadoc
jquery-detached
jdk-tool
jira
junit
ldap
mapdb-api
mailer:1.32
#matrix-auth
matrix-project
maven-plugin
metrics
mercurial
pam-auth
pipeline-build-step
pipeline-graph-analysis
pipeline-input-step
pipeline-milestone-step
pipeline-model-api
pipeline-model-declarative-agent
pipeline-model-extensions
pipeline-model-definition
pipeline-githubnotify-step
pipeline-github-lib
pipeline-rest-api
pipeline-stage-step
pipeline-stage-tags-metadata
pipeline-stage-view
pipeline-utility-steps
plain-credentials
scm-api
script-security
ssh-credentials
ssh-slaves
subversion
translation
variant
windows-slaves
workflow-aggregator
workflow-api
workflow-basic-steps
workflow-cps-global-lib
workflow-cps
workflow-durable-task-step
workflow-job
workflow-multibranch
workflow-scm-step
workflow-step-api
workflow-support
favorite
token-macro
terraform 
sse-gateway
cloudbees-bitbucket-branch-source 
blueocean-display-url
blueocean-pipeline-scm-api
pipeline-stage-step
blueocean-dashboard
blueocean-pipeline-editor
blueocean-rest
blueocean-git-pipeline
blueocean-pipeline-api-impl
blueocean-commons
blueocean-jwt
blueocean-web
blueocean-rest-impl
jenkins-design-language
blueocean-config
blueocean-bitbucket-pipeline
blueocean-github-pipeline
blueocean-personalization
blueocean-jira
blueocean-core-js
blueocean-events
blueocean-i18n
blueocean
blueocean-autofavorite
gitlab-plugin
service-now

**Comment by wills-gft** [comment]
The new image can be pulled from docker pull willsgft/jenkins-master:latest

**Comment by connor-mcshane** [comment]
Think we can close this off right?
