### ISSUE TITLE
Create Kubernetes Cluster with Jenkins hosted on to use for activator deployment pipeline #34

### ISSUE THREAD

**Issue by MatStacey** [tranquilitybase-io/tb-gcp#279]
We want to utilise Jenkins pipelines for deploying Activator applications onto clusters. We need an instance of Jenkins hosted on TB GKE to be able to execute these pipelines

**Comment by andy12838729** [comment]
You could just deploy a jenkins container on the current EC Cluster ? We also have the Eagle stack running on local machines - so that could be another option to start quickly

**Comment by RDHA-GFT** [comment]
Currently EC connects to Houston (Python App within a docker container with MySQL backend).
Houston maintains state from Eagle Console UI.
Houston then sends updated info to DAC.
DAC then initiates activator code based on information received form Houston.

At the moment DAC is doing the builds, managing deployments and also hosts the code. Should these activities be moved to CD cluster?

The creation of Solution/Workspace Tenant which is a stage prior to deploying an activator.

This stage will create a folder and a project  to deploy the activator into.

**Comment by MatStacey** [comment]
Hi,

Here is the current state of this issue:

the eagle_console.yaml file has been modified to include two new services hosted on the ec_gke cluster:

* DAC
* Jenkins

Both of these services should install on the cluster during deployment however they havent been tested to confirm whether they are working as intended or can be accessed.

The Jenkins Deployment YAML needs to modified to use the image created by @wills-gft 

@sunderhill-gft  made some changes for the DAC deployment however it still needs to be tested.

I would estimate 1-2 days work left to do some testing and make any required changes to the configurations.

**Comment by arvindclement** [comment]
Tested the Jenkins manifests that Caron has built and they are working as expected. Going to modify the landingzone terraform code to do the following:

1. Create 2 new namespaces like in issue #329 for ssp for self service portal and cicd for jenkins
2. Install Jenkins manifests into the cicd namespace

**Comment by arvindclement** [comment]
Tackled in issue #329 so closing this as it is redundant
