### ISSUE TITLE
Google Marketplace integration prep to  Bootstrap and Startup script

### ISSUE THREAD

**Issue by parmendra17** [tranquilitybase-io/tb-gcp#28]

**Comment by parmendra17** [comment]
Tranquility Base on GCP will initially be launched to GCP Market Place through a VM based integration approach. Following changes/additions are needed to enable this:
1. A Google Deployment Manager script to launch the Bootstrap VM with terraform installed
2. Enumeration of all the privileges for a service account that would be needed to unboxing of TBase and creat Landing Zone on the customer org node/folder
3. Market Place customer to create a service account with privileges enumerated in 2 and pass it to TBase launch from the Market Place 
4. TBase startup script should be capable of accepting and applying the service account when Landing Zone creation is kicked off by the customer from the Bootsrap VM

**Comment by dwalker1993** [comment]
Google Deployment Manager script successfully created launching the Bootstrap VM with customizable network resource attached, along with google cloud storage/IAM policies at project level. Still need to include startup script to kick off TBase and also need to edit deployment manager to use environment variabes .

**Comment by dwalker1993** [comment]
Something I found really useful, when attaching resources in the template scripts, use gcp types otherwise resources get created in the host project.

**Comment by dwalker1993** [comment]
Abstracting individual resources out of main project.py file and into template scripts

**Comment by dwalker26** [comment]
Updated GDM Scripts to include nat-gateway and moved terraform server and nat-gateway onto custom VPC. Access to terraform server done through IAP as no external ip address

**Comment by dwalker1993** [comment]
> Tranquility Base on GCP will initially be launched to GCP Market Place through a VM based integration approach. Following changes/additions are needed to enable this:
> 
> 1. A Google Deployment Manager script to launch the Bootstrap VM with terraform installed
> 2. Enumeration of all the privileges for a service account that would be needed to unboxing of TBase and creat Landing Zone on the customer org node/folder
> 3. Market Place customer to create a service account with privileges enumerated in 2 and pass it to TBase launch from the Market Place
> 4. TBase startup script should be capable of accepting and applying the service account when Landing Zone creation is kicked off by the customer from the Bootsrap VM

Will start working on point 2

**Comment by oscarmon7** [comment]
Superseded

**Comment by dwalker26** [comment]
Evidence

Thanks,
David

On 12 Mar 2020, at 11:17, oscarmon7 <notifications@github.com> wrote:

﻿

Superseded

**Comment by oscarmon7** [comment]
Deployment approach changed:
1. An configuration script will be downloaded and run from Cloudshell to:
- create a tb bootstrap project
- create a privileged service account
- enable APIs
2. Marketplace solution will be launched in the project created earlier
3. Deployment of Marketplace solution will deploy a bootstrap server using the SA created in step 1
4. User will SSH to bootstrap server in order to kick-off Terraform to deploy Landing Zone (Eagle console to be introduced shortly to replace manual activities)

**Comment by dwalker26** [comment]
[Image.jpeg]
Thanks,
David
________________________________

**Comment by dwalker26** [comment]
We need more certs guys keep up the great work

Thanks,
David
________________________________

**Comment by dwalker26** [comment]
Pawel you work for me now hahahaha

Thanks,
David
________________________________

**Comment by dwalker26** [comment]
Lie to hmrc

Thanks,
David

**Comment by dwalker26** [comment]
Thanks,
David

On 15 Apr 2020, at 11:21, andy12838729 <notifications@github.com> wrote:

﻿

Closed #28<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftranquilitybase-io%2Ftb-gcp%2Fissues%2F28&data=02%7C01%7C%7Cdde674e53f3042f5bb2608d7e126c929%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637225429001769166&sdata=T2v3bxi5rk4tEyjMerhY5HTgYkuSllpZJ4dQBY%2B4YvY%3D&reserved=0>.

**Comment by dwalker26** [comment]
180k is your upper limit, at best.

Thanks,
David

On 15 Apr 2020, at 11:21, andy12838729 <notifications@github.com> wrote:

﻿

Closed #28<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftranquilitybase-io%2Ftb-gcp%2Fissues%2F28&data=02%7C01%7C%7Cdde674e53f3042f5bb2608d7e126c929%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637225429001769166&sdata=T2v3bxi5rk4tEyjMerhY5HTgYkuSllpZJ4dQBY%2B4YvY%3D&reserved=0>.

**Comment by dwalker26** [comment]
Also, I’d chill out on the propaganda based justice you dish out. Corrupt states tend to fail.

Thanks,
David

On 15 Apr 2020, at 11:21, andy12838729 <notifications@github.com> wrote:

﻿

Closed #28<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftranquilitybase-io%2Ftb-gcp%2Fissues%2F28&data=02%7C01%7C%7Cdde674e53f3042f5bb2608d7e126c929%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637225429001769166&sdata=T2v3bxi5rk4tEyjMerhY5HTgYkuSllpZJ4dQBY%2B4YvY%3D&reserved=0>.

**Comment by dwalker26** [comment]
Sort your own house there buddy.




Thanks,
David

**Comment by dwalker26** [comment]
I think Soviet Russia fell Pawel, you know it about it more than me though so I guess you know what you’re doing.

Thanks,
David

On 18 Apr 2020, at 06:36, David Walker <Dwalker1993@hotmail.com> wrote:

﻿ Also, I’d chill out on the propaganda based justice you dish out. Corrupt states tend to fail.

Thanks,
David

On 15 Apr 2020, at 11:21, andy12838729 <notifications@github.com> wrote:

﻿

Closed #28<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftranquilitybase-io%2Ftb-gcp%2Fissues%2F28&data=02%7C01%7C%7Cdde674e53f3042f5bb2608d7e126c929%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637225429001769166&sdata=T2v3bxi5rk4tEyjMerhY5HTgYkuSllpZJ4dQBY%2B4YvY%3D&reserved=0>.

**Comment by dwalker26** [comment]
[Image.jpeg]
Thanks,
David
________________________________
