### ISSUE TITLE
Build prototype pipeline that takes arguments/parameters and calls terraform init, plan, and apply.

### ISSUE THREAD

**Issue by wills-gft** [tranquilitybase-io/tb-gcp#289]

**Comment by RDHA-GFT** [comment]
Ideally the pipeline should be taking input parameters direct from the Houston service which the EC is using to keep UI state.

**Comment by andy12838729** [comment]
> Ideally the pipeline should be taking input parameters direct from the Houston service which the EC is using to keep UI state.

Yes - but via the DaC so HS->DaC->Jenkins
