### ISSUE TITLE
Define pipeline specifications for the sample activator deploys

### ISSUE THREAD

**Issue by arvindclement** [tranquilitybase-io/tb-gcp#290]
Based on the sample activator deploy steps in https://github.com/tranquilitybase-io/tb-gcp/issues/281 come up with a diagram/Steps for MVP pipeline stages

**Comment by arvindclement** [comment]
1. The pipeline should have a web hook onto this repo (https://github.com/tranquilitybase-io/tb-activator-gft-base) and do the following.
2. Connect to the mysql database and read the following variables for the activator: project_id, zone,
subnet,region
3. Run terraform init
4. Run terraform validate
5. Run terraform plan with the -var option and list of variables in 2. with values
6. Run terraform apply
7. Inform the DAC service that it has run successfully

**Comment by connor-mcshane** [comment]
Discussion with Arvind, there are two clear variations on activator deployment. I have just listed some points here.

**Container Approach**
_pros_:
- **Easily repeatable**, is well suited for open source development.
- Somewhat **easier to orchestrate**, especially when combining activators.
- Easy to **security scans on images**.

**Terraform Pipeline Approach**
_pros_:
- Can easily **verify the terraform code** (terraform plan etc).
- Can easily query the **user if they wish to deploy X resources**.
- Easier to **identify issues with the environment and deploying**.

**Comment by arvindclement** [comment]
going to test both the approaches to see which is feasible and which is not. @wills-gft is going to test the source code approach and I will test the docker package approach. Going to use the jenkins master which Caron spun up on a VM to test this approach

**Comment by arvindclement** [comment]
Need to have a call with Simon Hill to see how he wants to build/call the CD job

**Comment by arvindclement** [comment]
One approach for the DAC to put the relevant activator details such as projectid, zone, region and subnetwork details as a .tfvars file in the activator repo as shown in the repo below.
https://github.com/arvindclement/tb_activator-devops

The above repo is an example for building the activator as a docker package but this would work for the source code approach as well. With this approach we would run the terraform plan, apply commands with -var-file option

**Comment by arvindclement** [comment]
Specifications for the Docker package approach
1.) Stage1: Download code from github and build the docker image and push it to repo
2.) Stage2: Once the push is done download the docker image and run with the following name for e.g base-activator-gft
3.) Stage3: Run the terraform init command
     docker exec -it base-activator-gft terraform init tb-activator-gft-base/
4.) Stage4:  Run the terraform validate command 
     docker exec -it base-activator-gft terraform  validate -var-file="tb-activator-gft-base/activator_name.tfvars" tb-activator-gft-base/
5.) Stage5: Run the terraform plan command 
     docker exec -it base-activator-gft terraform plan -var-file="tb-activator-gft-base/activator_name.tfvars" tb-activator-gft-base/
6.) Stage6: Run the terraform apply command
     docker exec -it base-activator-gft terraform apply -var-file="tb-activator-gft-base/activator_name.tfvars" --auto-approve tb-activator-gft-base/

**Comment by arvindclement** [comment]
Going to close this ticket and create one for building the docker package pipeline
