### ISSUE TITLE
Completely remove Vault from the base LZ deployment

### ISSUE THREAD

**Issue by RDHA-GFT** [tranquilitybase-io/tb-gcp#291]
Need to completely remove Vault from the default GCP LZ  deployment.
This includes removal of Vault GKE cluster, project folders and service account.

Vault will be an optional add-on but there will be a separate task to build this optional module.

**Comment by connor-mcshane** [comment]
Estimated todos:

- [ ] - remove Vault module.
- [ ] - remove creation of GKE cluster.
- [ ] - double check packer files to ensure code sections are referring to Vault modules etc
