### ISSUE TITLE
[Feature] Enable Cloud Audit read activity logging and export Audit logs to GCS bucket

### ISSUE THREAD

**Issue by scottholmangft** [tranquilitybase-io/tb-gcp#299]
**Is your feature request related to a problem? Please describe.**
Cloud Audit Logs maintains three audit logs for each Google Cloud project, folder, and organization: Admin Activity, Data Access, and System Event. Google Cloud services write audit log entries to these logs to help answer the questions of "who did what, where, and when?" within Google Cloud.

By default Admin modify activity, and system event logs are recored. This cannot be changed. Admin read activity needs to be enabled, and the Audit Logs exported to a GCS bucket to enable log analyse by third part tools like Splunk, ELK, Datadog, sysdig, etc

**Describe the solution you'd like**
Create a Terraform module that sets the default audit log config to include Admin Read on the root Org node. This setting is inherited by all child resources.

Create an organization level export, i.e. aggregated sink, to export all cloud audit logs to export to dedicated GCS buckets hosted by the shared-telemetry project.

Use a regional standard bucket with a multistage lifecycle rule:
- move data from standard to nearline storge after 30 days
- delete data after 365 days

Use the bucket UID as the bucket name and use labels to identity the function of the bucket.

**Describe alternatives you've considered**
none

**Additional context**
https://cloud.google.com/logging/docs/audit/best-practices

**Comment by rjmco** [comment]
In a brief conversation with Scott, we changed the following requirement 

> Create an organization level export, i.e. aggregated sink, to export all cloud audit logs to export to dedicated GCS buckets hosted by the shared-telemetry project.

to

Create an organization level export, i.e. aggregated sink, to export all **activity** and **system_events** cloud audit logs to export to dedicated GCS buckets hosted by the shared-telemetry project.
