### ISSUE TITLE
[Feature] Enable Cloud Logging export to GCS bucket

### ISSUE THREAD

**Issue by scottholmangft** [tranquilitybase-io/tb-gcp#302]
**Is your feature request related to a problem? Please describe.**
Currently Cloud Logs will be deleted by Google after 30 days, plus the logs are not accessible to 3rd party log analytics platforms for more fine grained analysis.

**Describe the solution you'd like**
Create a Terraform module to create an aggregated export sink at the Shared Services and Applications folders. Export to separate GCS buckets stored within the shared-telemetry project.

Use a regional standard bucket with a multistage lifecycle rule:
- move data from standard to nearline storge after 30 days
- delete data after 365 days

Use the bucket UID as the bucket name and use labels to identity the function of the bucket.

Use a logs filter to remove audit and system logs from the export, as these will be collected by the org level audit logs export.

**Describe alternatives you've considered**
none

**Additional context**
https://cloud.google.com/logging/docs/export/aggregated_sinks
https://cloud.google.com/logging/docs/export/using_exported_logs

**Comment by arvindclement** [comment]
@Waterhouse-GFT have a look at this PR for the packer .json changes do the same for your new folder and the image should work. 
https://github.com/tranquilitybase-io/tb-gcp/pull/374

Let me know if you have any problems
