### ISSUE TITLE
Get Tranquility Base ready for demonstration [ISSUE]

### ISSUE THREAD

**Issue by connor-mcshane** [tranquilitybase-io/tb-gcp#308]
## Purpose
We need to be able to demo Eagle Console deployed from the Landing zone with the following attributes:
- private ips.
- dns lookup for eagle console endpoint.

## Estimated Work to Complete
Steps to complete the task
1. Create demo branch
2. incorporate changes from #255 and #256.
3. Setup DNS record set to be added to on creation of EC GKE.
4. Add Eagle Console container to the EC GKE manifest so it is deployed on EC GKE.

## Definition of Done
Landing Zone and Eagle Console (front end only) deployment end to end (automated) off any branch

## Related Issues
#255  and #256

**Comment by karwootang-gft** [comment]
https://console.cloud.google.com/gcr/images/tranquility-base-images/GLOBAL/tb-eagle-console?project=tranquility-base-images&gcrImageListsize=30

You can use the images here, tagged with integration.

**Comment by Salles-FA** [comment]
I've just moved the tags "landingzone".

We are only moving it manually when there is an acceptable level of stability. Therefore, images tagged with 'landingzone' are preferable.
