### ISSUE TITLE
[Feature] Deploy HA VPN with Terraform GCP-to-GCP

### ISSUE THREAD

**Issue by RDHA-GFT** [tranquilitybase-io/tb-gcp#326]
** NOTE: Issued renamed and updated to focus on GCP-to-GCP HA VPN. New issues have been created for GCP-to-AWS, and GCP-to-onprem **

**Is your feature request related to a problem? Please describe.**
Deploy HA VPN with a 1-peer-2-addresses configuration on Google Cloud Platform (GCP) between GCP projects

**Describe the solution you'd like**
The ability to create an HA VPN deployment with terraform which can be triggered by parameters entered through the Eagle Console. The Terraform module must create a HA VPN between two GCP projects within the same GCP Organization.

Example Terraform code:
https://cloud.google.com/community/tutorials/deploy-ha-vpn-with-terraform

**Additional context**
Need to consider secrets management for the pre-shared key, this should not be saved in plain text or database
Consideration on where TF state file is kept and whether this is s separate configuration or update of existing TF configuration.

**Comment by Salles-FA** [comment]
Issue related to: https://github.com/tranquilitybase-io/TranquilityBase/issues/31

**Comment by RDHA-GFT** [comment]
https://cloud.google.com/vpn/docs/how-to/choosing-a-vpn
https://cloud.google.com/files/CloudVPNGuide-UsingCloudVPNwithCiscoASA.pdf

**Comment by scottholmangft** [comment]
The requirements for this issue has become too broad. Therefore the issue will be renamed to focus delivery GCP-to-GCP only. Another two tickets will be created to cover gcp-to-aws, and gcp-to-onprem. new issue numbers to follow.
