### ISSUE TITLE
tb-config-creator should add billing account and root id as project labels to the bootstrap project[ISSUE]

### ISSUE THREAD

**Issue by connor-mcshane** [tranquilitybase-io/tb-gcp#332]
## Purpose
To ensure that the billing account and folder is only needed to be handled once.

## Relevant Info
Links to resources, documentation etc.

## Estimated Work to Complete
Steps to complete the task
1.  Use gcloud commands in tb-config creator to tag the bootstrap project with billing_account id and tb-folder id with labels.
2. In the deployment manager script and in the bootstrap-init.sh script, makesure that the billing account and the tb-folder-id is pulled from the project labels.

## Definition of Done
Fully working deployment, where the billing account and the root id is only entered once by the user.

## Related Issues
links to other issues

**Comment by Waterhouse-GFT** [comment]
Not needed due to refactoring of bootstrapping stage.
