### ISSUE TITLE
[Feature] Grafana dashboard access

### ISSUE THREAD

**Issue by scottholmangft** [tranquilitybase-io/tb-gcp#339]
**Is your feature request related to a problem? Please describe.**
Grafana dashboard is deployed as part of the OSS Istio deployment now used in the Eagle Console GKE deployment. Grafana only available via IP address.

**Describe the solution you'd like**
Grafana needs to be made accessible via a name registered with Cloud DNS deployed into the Shared VPC. The dashboard via the windows bastion server.

e.g. grafana.private.landing-zone.com

The must be configured on the Eagle Console GKE cluster, but developed in a way to enable use for of GKE deployments

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by RDHA-GFT** [comment]
Issue completed
