### ISSUE TITLE
CI/CD setup to deploy Tranquility Base and run post deploy automation tests

### ISSUE THREAD

**Issue by dwalker1993** [tranquilitybase-io/tb-gcp#34]
Considerations:
Before tackling this, we should look to modularise the tf deployment and trigger off different pipelines depending on which section of the code has been edited.

At the moment we have the one TF state that describes the deployment of these resources.
![image](https://user-images.githubusercontent.com/10451364/82055378-4c82a280-96b8-11ea-9e6f-370595288779.png)

First pass modularisation (draft):
1.  Bootstrap project and configuration without a tf state configuration kept as is.

2.  LZ Project creation and Networking stored as its own state in the bootstrap project
![image](https://user-images.githubusercontent.com/10451364/82055427-5f957280-96b8-11ea-8c1c-09dea54b48e5.png)

3. GKE configuration for eagle console and other cluster configurations in another TF state file
![image](https://user-images.githubusercontent.com/10451364/82055478-76d46000-96b8-11ea-99c5-97b587491b31.png)

to deploy the whole thing would still require a bash script (or pipeline steps) but it should make it easier to modify individual parts.

**Comment by connor-mcshane** [comment]
Narish has recommended this sort of structure 
![image](https://user-images.githubusercontent.com/10451364/82056394-d121f080-96b9-11ea-9fc1-32d51c49ef05.png)

**Comment by RDHA-GFT** [comment]
Will be covered by refresh
