### ISSUE TITLE
[BUG] EC cluster has ephemeral storage issue, pods being evicted

### ISSUE THREAD

**Issue by stuartrl07** [tranquilitybase-io/tb-gcp#342]
**Describe the bug**
With the latest way istio is being installed there is an issue on the EC cluster when first created, pods are being evicted and terminated with the error "low on ephemeral storage", it does not happen every deployment. It leads to the private ingress gateway being removed and replaced with an external one.

**To Reproduce**
Do a normal tb-welcome deployment. Look at the deployments and workloads on eagle console cluster. Should see that some were evicted three times before being stable, with the error about epehmeral storage running low.

Looking at it briefly it looks like an issue with undefined storage/possibly an excess amount of logs being created with no clean up
https://access.redhat.com/solutions/4367311

**Comment by arvindclement** [comment]
This issue was addressed and resolved as part of #382
