### ISSUE TITLE
[ISSUE] Research effect of enabling skip default VPC Org policy on TB

### ISSUE THREAD

**Issue by scottholmangft** [tranquilitybase-io/tb-gcp#349]
## Purpose
The "skip default VPC creation Org policy" enables org admins to prevent the creation of the default VPC on project creation. The default VPC deploys subnets in every region, and creates 0.0.0.0/0 allow firewall rules for SSH & RDP, which exposes internal cloud resources unnecessarily. Best practice dictates that the default VPC be deleted, and a new custom VPC be created to suit requirements. 

When this Org policy is enabled the TB deployment fails, as TF attempts to delete the default VPC.

Determine how to refactor the code to allow for this Org policy to be used.

## Relevant Info

Provisioner issue thread: https://github.com/terraform-providers/terraform-provider-google/issues/3582

## Definition of Done
Determine a solution to allow use of this org policy.

**Comment by Waterhouse-GFT** [comment]
Have tested a deploy of master in the SkipDefaultNet folder, with modified config creator and it deployed with no issues, afte having moved to 3.3 provider.
