### ISSUE TITLE
[Feature] SCC AUDIT_LOGGING_DISABLED on all projects

### ISSUE THREAD

**Issue by scottholmangft** [tranquilitybase-io/tb-gcp#354]
**Is your feature request related to a problem? Please describe.**
By default Audit logs only track admin modification. Admin reads, and Data write/reads are not enabled by default. To comply with CIS/NIST/PCI/ISO these need to be enabled on each project.

**Describe the solution you'd like**
Enable Audit logging to track Admin reads, and Data write/reads to comply with CIS/NIST/PCI/ISO these need to be enabled on each project.

**Describe alternatives you've considered**

**Additional context**

**Comment by adamgft** [comment]
Closed due to overlapping feature with issue-299
