### ISSUE TITLE
Remove Ingress Firewall Rules

### ISSUE THREAD

**Issue by dwalker1993** [tranquilitybase-io/tb-gcp#36]
Suggested tasks:
- Create the bastion servers and hosting projects
- Make the service load balancers internal
- Restrict firewall rules that allow source ranges 0.0.0.0/0 to known sources or alternatively IAP source ranges
- other tasks unforeseen at the moment

**Comment by scottholmangft** [comment]
Need to check whether this has been done.

**Comment by RDHA-GFT** [comment]
The default ingress access has been removed and remote access to the bastion hosts are now only allowed through IAP
