### ISSUE TITLE
[Feature] Project labels needed to track costs of projects deployed within a TB LZ instance

### ISSUE THREAD

**Issue by scottholmangft** [tranquilitybase-io/tb-gcp#375]
**Is your feature request related to a problem? Please describe.**
Labels can be used to assign non-GCP service specific attributes to the majority of Google Cloud resources.

Common attributes include business units/environment/cost-code/stakeholder/tech-owner/business-owner/etc.

Labels assigned to projects are captured by the billing service, and are exported to BigQuery as part of the billing export.

Reports can be generated to filter of the labels; either through the native billing reporting tool, or via visualising the billing info found in the BQ export using tools such as DataStudio.

Labels are not being automatically applied to TB projects during deployment. Labels are sometime added manually.

**Describe the solution you'd like**
Labels need to be added to each project deployed as part of TB. Terraform provides a facility to automatically apply labels to resources deployed by TF.

Please refer to the following repo for a recommended approach to project labelling.

https://github.com/nhsy/gcp-labels

The -var-files: switch and the <filename>.tfvars file

The first iteration of automated labelling is to assign the following labels  label (key:value pair) to the bootstrap project and all landing zone projects, and folders from the top level TB folder down.
- client:tranquility-base
- created-by:[username]

**username = the Cloud Identity account used to initiate the that kicked off the deployment. This must be picked automatically from the environment**

There will be further feature issues to improve labelling.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by andy12838729** [comment]
The DaC should be adding labels to folders/projects/accounts and resources at the moment. This feature is in the DaC and central CD service.
