### ISSUE TITLE
IAM ownership model

### ISSUE THREAD

**Issue by dwalker1993** [tranquilitybase-io/tb-gcp#39]
Create Terraform module to create the following Cloud Identity user groups

OrgAdmin@domainname.com
BillingAdmin@domainname.com
SecurityAdmin@domainname.com
NetworkAdmin@domainname.com
CloudEngineer@domainname.com
Developer@domainname.com

Permission set for each initial group
Create the initial groups on the organization
Implementing the Terraform code that binds the groups/IAM_role to resources deployed

**Comment by oscarmon7** [comment]
The creation of groups is only allowed to GSuite Groups administrators

**Comment by RDHA-GFT** [comment]
This assumes the use of Cloud Identity, will likely need different modules based on different IDPs.
Also need to define the mapping of Identities to IAM roles.

**Comment by RDHA-GFT** [comment]
Superseded by #491
