### ISSUE TITLE
[Feature] Deploy HA VPN with Terraform GCP-to-AWS

### ISSUE THREAD

**Issue by scottholmangft** [tranquilitybase-io/tb-gcp#391]
Is your feature request related to a problem? Please describe.
Deploy HA VPN with a between a Google Cloud Platform (GCP) project, and AWS account.

Describe the solution you'd like
The ability to create an HA VPN deployment with terraform that can be triggered by parameters entered through the Eagle Console. The Terraform module must create a HA VPN between a GCP project and an AWS account.

Example Terraform code:
https://cloud.google.com/community/tutorials/deploy-ha-vpn-with-terraform

Additional context
Need to consider secrets management for the pre-shared key, this should not be saved in plain text or database
Consideration on where TF state file is kept and whether this is s separate configuration or update of existing TF configuration.

**Comment by Salles-FA** [comment]
Define fields in WAN VPN connection to AWS vendor

- https://github.com/tranquilitybase-io/tb-eagle-console/issues/155

**Comment by Salles-FA** [comment]
Issue related to: tranquilitybase-io/TranquilityBase#31
