### ISSUE TITLE
Integrate the eagle console service account file into Jenkins

### ISSUE THREAD

**Issue by arvindclement** [tranquilitybase-io/tb-gcp#394]
## Purpose
This is required so that Jenkins has the authorisation to build infrastructure in gcp so that activator are deployed

## Estimated Work to Complete
Steps to complete the task
1. https://cloud.google.com/solutions/using-jenkins-for-distributed-builds-on-compute-engine
2. using the above link as reference integrate the service account file created as part of the eagle console into Jenkins

## Definition of Done
When DAC called Jenkins to deploy the activator it does it without getting authorisation errors

## Related Issues
#380

**Comment by arvindclement** [comment]
Going to look at https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity to allow jenkins to install onto projects under the tranquility base folder. This talks about creating  a kubernetes service account file and then binding to the gcp service account file using workload-identiy and also associating the binding only to the jenkins/cicd namespace so takes care of security as well

**Comment by arvindclement** [comment]
the kubernetes creation module needs to have this attribute enabled workload_identity_config for e.g as part of the gke.tf

# Enable Workload Identity
    workload_identity_config {
      identity_namespace = "${var.project_id}.svc.id.goog"
    }
So Steps required are 
1.) enable workload identity in the gke-cluster
2.) use the service account that is created for the ec cluster
3.) Create K8 service account for the cicd namespace
4.) IAM policy binding like the e.g below
gcloud iam service-accounts add-iam-policy-binding \
  --role roles/iam.workloadIdentityUser \
  --member "serviceAccount:project-id.svc.id.goog[k8s-namespace/ksa-name]" \
  gsa-name@project-id.iam.gserviceaccount.com
5.) Add annotation to the K8 service account 
kubectl annotate serviceaccount \
  --namespace k8s-namespace \
  ksa-name \
  iam.gke.io/gcp-service-account=gsa-name@project-id.iam.gserviceaccount.com
6.) Test

**Comment by wills-gft** [comment]
Actual steps carried out to test 

```
gcloud container clusters update devcluster --workload-pool=jenkins-test-env.svc.id.goog --region europe-west2
gcloud container node-pools update default-pool --cluster=devcluster --workload-metadata=GKE_METADATA --region europe-west2

gcloud iam service-accounts create activator-dev-sa                                                                         
Created service account [activator-dev-sa].


kubectl create namespace cicd
kubectl create serviceaccount --namespace cicd jenkins-sa


gcloud iam service-accounts add-iam-policy-binding --role roles/iam.workloadIdentityUser --member "serviceAccount:jenkins-test-env.svc.id.goog[cicd/jenkins-sa]" activator-dev-sa@jenkins-test-env.iam.gserviceaccount.com
Updated IAM policy for serviceAccount [activator-dev-sa@jenkins-test-env.iam.gserviceaccount.com].
bindings:
- members:
  - serviceAccount:jenkins-test-env.svc.id.goog[cicd/jenkins-sa]
  role: roles/iam.workloadIdentityUser
etag: BwWqe95wtGs=
version: 1


kubectl annotate serviceaccount --namespace cicd jenkins-sa iam.gke.io/gcp-service-account=activator-dev-sa@jenkins-test-env.iam.gserviceaccount.com


Run the following in the workload pod used to test.

k run -it --image google/cloud-sdk:slim --serviceaccount jenkins-sa --namespace cicd workload-identity-test
gcloud services enable compute.googleapis.com
gcloud services enable servicemanagement.googleapis.com
gcloud services enable cloudresourcemanager.googleapis.com
gcloud services enable cloudresourcemanager.googleapis.com
gcloud services enable storage-api.googleapis.com
```

**Comment by arvindclement** [comment]
Looked at enabling in the kubernetes cluster creation module as part of the landingzone but the terraform provider is in beta and the version is > than 3.10 we use versions 2.5 in our landingzone and it is hardcoded in quite a few modules and not sure what the implications of changing the google-beta version would be. Hence we decided to do the steps manually as listed above but the enabling of workload identity and upgrading of the gke node pools takes forever(min 2 hours) and not a viable option for integrating this in the landingzone.

**Comment by arvindclement** [comment]
Finding so far:
1.) The workplace identity works but the problem we have with deploying with terraform is it looks for a credentials file so we need to have this mounted as part of the Jenkins pod
2.) Also there is a limitation with respect to the google-beta provide version it has to be 3.10 and greater
3.) So keeping these two in mind we have decided not to go down the workload identity route instead we are going to use the service account created as part of the landingzone, mount that into Jenkins as a secret and then use that to deploy into gcp
4.) Also use the kubectl get secret ec-service-account -n default -o yaml | sed s/"namespace: default"/"namespace: cicd"/ | kubectl apply -n cicd -f - to copy the secret over to the cicd namespace 
5.) modify the Jenkins ur to have the secret and mount it as a volume in the pod as attached

**Comment by arvindclement** [comment]
Changes need to be done on the dac k8 deployment yaml and eagle console with respect to the jenkins url and also the client id

**Comment by arvindclement** [comment]
PR raised with all the changes
