### ISSUE TITLE
[Feature] Create Terraform for HA deployment of Citrix Cloud Connectors  

### ISSUE THREAD

**Issue by adamgft** [tranquilitybase-io/tb-gcp#402]
**Is your feature request related to a problem? Please describe.**

To handle the communication between Citrix Cloud and the Customer Resource Location, two Citrix Cloud Connectors need to be created and configured to facilitate this communication. 

**Describe the solution you'd like**

Two configuration need to be configured: 
One allowing a single Cloud Connector instance to be created and another with two Cloud Connector instances created to provide a HA and non-HA solution. 

Requirements:
- Disable Internet Explorer Enhanced Security Configuration (IE ESC)
- Join to an existing Active Directory domain on startup
- Instances need to be in different zones within the same region

**Describe alternatives you've considered**

**Additional context**
https://docs.citrix.com/en-us/citrix-virtual-apps-desktops-service/install-configure/cloud-connectors-install.html
https://docs.citrix.com/en-us/citrix-cloud/citrix-cloud-resource-locations/citrix-cloud-connector.html
https://docs.citrix.com/en-us/citrix-cloud/citrix-cloud-resource-locations/citrix-cloud-connector/technical-details.html
https://docs.citrix.com/en-us/citrix-cloud/citrix-cloud-resource-locations/citrix-cloud-connector/installation.html

**Comment by scottholmangft** [comment]
Is it worth splitting this into separate issues? First non-HA, and the other HA?

**Comment by adamgft** [comment]
Yes that would be valuable, I will split this ticket up into two. One for HA and one for non-HA
