### ISSUE TITLE
Jenkins Configuration As Code to Automate Jenkins instal config part of LandingZone deploy

### ISSUE THREAD

**Issue by arvindclement** [tranquilitybase-io/tb-gcp#433]
## Purpose
Currently the only things that need manual config and creation with respect to Jenkins after the landingzone is deployed is 
1.) Enable proxy compatibility (resolve the crumb issue)
2.) Create a docker global tool
3.) Create a github private user
The above currently is being done via the Jenkins UI and need this to be automate using Jenkins AS Code
4.) Add an initial Jenkins job that will deploy activators from git repos. The setup of the job is described here - https://confluence.gft.com/pages/viewpage.action?pageId=239338606

## Relevant Info
https://www.praqma.com/stories/start-jenkins-config-as-code/

## Estimated Work to Complete
Steps to complete the task
1. Steps similar to the one detailed in the link above

## Definition of Done
When the landingzone is deployed we would have Jenkins running with the above 3 configs set

**Comment by sunderhill-gft** [comment]
added another config setup concerning Jenkins activator deploying job

**Comment by Salles-FA** [comment]
@zain-GFT,

Is this a finished work? How is it working? Could you describe the solution please?

**Comment by zain-GFT** [comment]
This task has been completed.

Below is the solution:

- The Jenkins CASC plugin is used to setup the configuration of a jenkins instance on startup.

- This plugin requires the use of a YAML file to describe the intended configuration of the jenkins instance. This YAML file has been created in the same directory as the DockerFile and can be found here:
https://github.com/tranquilitybase-io/tb-jenkins/blob/master/jenkins/Jenkins%20Cluster/gcp/Docker-image/Docker-files/jenkins.yaml

- The jenkins.yaml file above contains the detail of the jenkins configuration. This includes the requirements set out in this issue which were:

1. Enable proxy compatibility (resolve the crumb issue)
2. Create a docker global tool
3. Create a github private user
4. Add an initial Jenkins job that will deploy activators from git repos.

- Once Jenkins is started, this configuration file is applied and those steps are applied automatically, preventing the need to do those steps manually.

- The plugin uses an environment variable "CASC_JENKINS_CONFIG" which is specified in the DockerFile, the aim of this environment variable is to inform the plugin the location of the YAML configuration file.
