### ISSUE TITLE
Jenkins as code for the Activator Jobs

### ISSUE THREAD

**Issue by arvindclement** [tranquilitybase-io/tb-gcp#434]
## Purpose
Currently the activator jobs are run as pipeline scripts via the gui that needs to be change as pipeline code that triggers a build
Change needs to happen for the following activators
https://github.com/tranquilitybase-io/tb-activator-gft-base
https://github.com/tranquilitybase-io/tb-gcp-hpc-activator

This issue ties in with changes in tb-gcp-dac. DAC needs to be able to call Jenkins jobs and get responses from them. See [issue 113](https://github.com/tranquilitybase-io/tb-gcp-dac/issues/113)

## Relevant Info
https://www.jenkins.io/doc/book/pipeline-as-code/

## Estimated Work to Complete
Steps to complete the task
1. Write a Jenkins job that will run a Jenkinsfile from a given git repository passed as a parameter. 
2. Export this Jenkins job and add it as an initial job in the Tranquility Base deployed Jenkins server image. (is this done in tb-cicd-orchestration? how is the jenkins image used in the kubernetes config created?)
3. The Jenkins job will need to accept the following parameters:

- repourl - the git repo URL for the activator being deployed

- projectid - the GCP project id where the activator will be deployed

- activator_params - key/value list of parameters required by the activator. This can be blank if no parameters are required.

- job_unique_id - a unique job id that will allow the Jenkins job to be tracked. 

A typical call of the Jenkins job will look like this:
`curl -X POST "jenkins-master-svc.cicd/buildByToken/buildWithParameters?job=Activator-Pipeline&token=activatorbuild&repourl=https://github.com/tranquilitybase-io/tb-activator-gft-base.git&projectid=development-sqesu9-dmt4zn1g&activator_params=size=1000,region=europe-west2&job_unique_id=ABCDEF"`

4. Add a Jenkinsfile to each current activator - tb-activator-gft-base and tb-gcp-hpc-activator. These Jenkinsfiles will have access to the above parameters.

## Definition of Done
The Jenkins job can deploy an activator with a given git repo if the activator has a Jenkinsfile that can be called.

**Comment by andy12838729** [comment]
Jenkins job should also be viewable in EC as part of the activator view screen. Ie we need to store a reference to where the job can be found so the code can be displayed in the UI

**Comment by sunderhill-gft** [comment]
Added issue #508.
DAC needs a standard Jenkins user in order to monitor Jenkins builds.  Currently testing using the admin user which is the only user set up.

**Comment by andy12838729** [comment]
Maybe we need the DevOps section and one tile is “CI/CD Setup”. In that tile, if you select Jenkins the UI asks for a username and pwd ?

**Comment by Salles-FA** [comment]
@zain-GFT,

Is this a finished work? How is it working? Could you describe the solution please?

**Comment by zain-GFT** [comment]
This task has been completed.

Below is the solution:

- A Jenkins job that runs a Jenkinsfile from a given git repository passed as a parameter has been created and can be found here:  https://github.com/tranquilitybase-io/tb-jenkins-jobs/blob/main/activator_pipeline.groovy

- This job is added to the jenkins instance automatically. This is done using the seed job which was part of the jenkins.yaml file which was created on issue-433. That seed job contains a logic that searches for .groovy files in the https://github.com/tranquilitybase-io/tb-jenkins-jobs repo.

- After finding the .groovy files in the respective repo, the seed job then adds them as jobs automatically.

- The job "activator_pipeline" which is created out of the "activator_pipeline.groovy" file, allows for the parameters listed in the issue to be passed. These parameters are:

1. repourl - the git repo URL for the activator being deployed

2. projectid - the GCP project id where the activator will be deployed

3. activator_params - key/value list of parameters required by the activator. This can be blank if no parameters are required.

4. job_unique_id - a unique job id that will allow the Jenkins job to be tracked.

- A JenkinsFile can be found in each respective Activator repo and that JenkinsFile has access to the above parameters.
