### ISSUE TITLE
Review permissions of all Service Accounts used in TB	 

### ISSUE THREAD

**Issue by dwalker1993** [tranquilitybase-io/tb-gcp#44]
Currently, TB scripts create many Service Accounts (eg. bootstrap-sa, activator-sa, etc) and assign to them many roles establishing security policies on different levels (organization, folders, projects, resources). 

The resulting granted permissions need to be verified to narrow them to minimally required.

**Comment by oscarmon7** [comment]
Related to #172. See attachment https://github.com/tranquilitybase-io/tb-gcp/files/4306702/iam.issue-172.xlsx

**Comment by RDHA-GFT** [comment]
Check TB reference documentation and come up with recommendations

**Comment by RDHA-GFT** [comment]
When Dan Martin is back on bench can look to work on this.
