### ISSUE TITLE
HPC Binaries bucket permissions for TB service Accounts

### ISSUE THREAD

**Issue by arvindclement** [tranquilitybase-io/tb-gcp#440]
## Purpose
As part of the HPC activator binary store we need a project with a bucket to hold the binaries and the activator service account that gets created as part of the landingzone needs to have access to download these binaries

## Relevant Info

https://serverfault.com/questions/746866/giving-access-on-google-cloud-storage-to-users-outside-google-apps-domain
https://cloud.google.com/iam/docs/granting-changing-revoking-access
https://cloud.google.com/storage/docs/uniform-bucket-level-access
https://cloud.google.com/storage/docs/json_api/v1/bucketAccessControls

## Estimated Work to Complete
Steps to complete the task
1. Project already created called 
tb-priv-activators-resources
2. Bucket already created in there called tb-gcp-hpc-activator-resources
3. we need to add read/write permission for the activator service account to the bucket in 2 so that it can copy the binaries from the bucket

## Definition of Done
When the activator is deployed the anisble should be able to read the binaries and deploy the the hpc code into the project

## Related Issues
https://github.com/tranquilitybase-io/TranquilityBase/issues/67

**Comment by arvindclement** [comment]
Need to evaluate how we can incorporate giving read access i.e objectViewer to the bucket, to the activator serviceaccount that gets created as part of the landingzone. This could be the case in future if any other activator needs binaries to be copied can be stored as a folder in that bucket and read permissions given to the serviceaccount that needs it. 
Also the HPC activator deploy pipeline has been changed so that it copies that contents of this bucket into a bucket in the projec t that it is deploying and then deploys the activator

**Comment by arvindclement** [comment]
Solution Found but need peer review to check if this is actually feasible. The solution is using signed url 
1. Zip the Binaries into a single file as signed urls work on a file by file basis
2. Request access to the binaries 
3. Admin gives you a limited duration access using signedurl using the below command
4. gsutil -i <service account email> signurl -d 10m -u gs://<bucket>/<object>
5. use the signedurl in the Dockerfile which would then download the binaries in the docker image
6. Documentation would be updated in the Activator Dockerfile section with the steps
7. The HPC activator pipeline would copy those binaries into the bucket in the project and then use to install HPC

**Comment by rjmco** [comment]
@arvindclement sounds like a good plan as long as we ensure that on step 5 the URL is not hardcoded on the Dockerfile.

**Comment by arvindclement** [comment]
Ok tested it using my project now would need to upload to tb-priv-activators-resources and test. For testing the following needs to happen
1.) service account needs to be created in the tb-priv-activators-resources project with storage admin permissions
2.)Upload the hpc.zip file into the gs://tb-gcp-hpc-activator-resources/
3.) Generate signed url for 1h duration and use it while building the dockerfile 
3.) Test run the HPC pipeline and see if it picks up from that bucket

**Comment by RDHA-GFT** [comment]
Hi Dan, Can you also check this issue

**Comment by Nzastudios** [comment]
Spoke with Arvind and this can be closed.
Project this was associated to: tb-priv-activators-resources [Production]
