### ISSUE TITLE
Add the Jenkins Service as part of the istio service mesh

### ISSUE THREAD

**Issue by arvindclement** [tranquilitybase-io/tb-gcp#441]
## Purpose
IF this is done then we don't need a separate IP to access Jenkins it can be done using the eagleconsole dns name and /jenkins-service path

## Estimated Work to Complete
Steps to complete the task
1. Create a separate gateway for jenkins in the cicd namespace
2. Create a sepate virtualservice and destination rule so that when you hit the private gateway endpoint with a /jenkins-service
it should bring up the jenkins service
3. The jenkins kubernetes service config needs to be changed from a loadbalancer to a clusterip, the changed yaml file is given below change needs to happen in the tb-gcp/tb-gcp-tr/shared-dac/jenkins-master.yaml
########################
apiVersion: v1
kind: Service
metadata:
  name: jenkins-master-svc
  namespace: cicd
  labels:
    app: jenkins-master
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 50000
    targetPort: 50000
    protocol: TCP
    name: slave
  selector:
    app: jenkins-master
#############################

## Definition of Done
eagle-console.private.landing-zone.com/jenkins-service should bring up the Jenkins service

## Related Issues
links to other issues

**Comment by Salles-FA** [comment]
@zain-GFT,

Is this a finished work? How is it working? Could you describe the solution please?
