### ISSUE TITLE
Investigate and write Groovy code test and skip image creation stage in HPC Jenkins pipeline.

### ISSUE THREAD

**Issue by wills-gft** [tranquilitybase-io/tb-gcp#448]

**Comment by arvindclement** [comment]
Looked at the when clause to do the skip stage when object present and also modified the pipeline but looks like the test isn't working as expected need to dig further

**Comment by arvindclement** [comment]
Ok the pipeline has been modified to skip stage when the following conditions are met
1.) When the bucket for the binaries already exists
2.) When the custom images are created

sample snippets are here 
		stage('Binaries Bucket Create Stage')  {
			when { 
			    expression { sh(script: "gsutil ls | grep $BUCKETNAME", returnStatus:true) }
			}
			steps {
			    sh "gsutil mb -p $projectid  -l europe-west2 gs://$BUCKETNAME/"
		    }   
        }   

##### image creation #####

        stage('Run HPC Create Images Process') {
		  when { 
			    expression { sh(script: "gcloud compute images list --filter='$projectid'", returnStatus:true) }
			}
          steps {
              sh '${DockerCMD} exec ${ACTIVATORNAME}$BUILD_NUMBER cat ${ACTIVATORNAME}/bootstrap/kms_key.out > /tmp/kms_key.out'
			  sh "${DockerCMD} exec ${ACTIVATORNAME}$BUILD_NUMBER make KMS_KEY=`cat /tmp/kms_key.out` PROJECT_ID=$projectid createimages -C ${ACTIVATORNAME}/"
            }  
        }
