### ISSUE TITLE
LZ requires SSP docker image already published in GCR

### ISSUE THREAD

**Issue by dwalker1993** [tranquilitybase-io/tb-gcp#45]
Currently, Landing Zone Terraform script requires a Docker image with SSP backend in order to deploy SSP backend to its Kubernetes cluster. The Landing Zone TF script takes this image from GCR (Google Container Repository) from the following location: gcr.io/gft-microservices-activator/self-service-portal 
Currently, such docker image with SSP backend is published to the "GFT Microservices Activator" project manually.

More strategic solution should be proposed and implemented that would be automated and that would not use the "GFT Microservices Activator" project's container repository

**Comment by oscarmon7** [comment]
The SSP Docker image  has been superseded by the EC UI and (mock server) backend implemented in repo _tb-eagle-console_.
