### ISSUE TITLE
The iTop portal is available through an HTTP and not through a HTTPS endpoint 

### ISSUE THREAD

**Issue by dwalker1993** [tranquilitybase-io/tb-gcp#46]
iTop is available through the GKE cluster named `gke-opt` which is hosted on the shared-operations project under the Shared Services folder. At the moment traffic to iTop is routed through the Istio service mesh configured on the GKE cluster. If iTop is to be used beyond a demonstration tool, iTop's deployment configuration needs to be changed to secure access to it, either by configuring Istio or by using any other means (e.g. load balancer with self-signed x509 certificate)

**Comment by scottholmangft** [comment]
has some overlap with another issue
https://github.com/tranquilitybase-io/tb-gcp/issues/36

**Comment by RDHA-GFT** [comment]
No longer relevant
