### ISSUE TITLE
terraform-server (aka terraform-bastion) must have external IP removed. Deploy Cloud NAT for external access.

### ISSUE THREAD

**Issue by dwalker1993** [tranquilitybase-io/tb-gcp#47]
"Join the terraform-server to the newly created custom VPC, and remove the external IP.
Deploy Cloud NAT, and direct non-internal network traffic to use the Cloud NAT for external access.
IAP for TCP is needed to provide remote access to the terraform-server"

**Comment by oscarmon7** [comment]
In the Marketplace solution NAT Gateway service is provided via VM configured as a NAT (GDM does not support Cloud NAT atm).
