### ISSUE TITLE
[Feature] Add persistence for services in Eagle Kubernetes cluster

### ISSUE THREAD

**Issue by sunderhill-gft** [tranquilitybase-io/tb-gcp#470]
When the Kubernetes cluster is restarted then data in the MySQL database and Redis server is lost. 

Add persistence to each of these containers in the cluster or replace with the equivalent cloud service. Jenkins already has a persistence volume.
e.g. for GCP, CloudSQL for MySQL, Memorystore for Redis

An example implementation for Redis [here](https://estl.tech/deploying-redis-with-persistence-on-google-kubernetes-engine-c1d60f70a043)

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/tb-gcp-dac/issues/54
