### ISSUE TITLE
[Feature] Parameterise citrix vda filename in bootstrap, packer and deploy vda powershell

### ISSUE THREAD

**Issue by zi01farm** [tranquilitybase-io/tb-gcp#486]
**Is your feature request related to a problem? Please describe.**
Further improvements can be made to handle future citrix binary versions, currently the name is hard coded and thus is not flexible

**Describe the solution you'd like**
Parameterise citrix vda filename in bootstrap, packer and deploy vda powershell

**Describe alternatives you've considered**
The solution proposed satisfies the current requirements

**Additional context**
N/A

**Comment by adamgft** [comment]
ticket moved to citrix board
