### ISSUE TITLE
[Feature] Upload citrix vda binary from local machine in bootstrap

### ISSUE THREAD

**Issue by zi01farm** [tranquilitybase-io/tb-gcp#487]
**Is your feature request related to a problem? Please describe.**
Current implementation requires the user to upload the citrix vda binary file manually to a storage bucket inside the project. A better approach would instead have it automatically uploaded from the user's local machine

**Describe the solution you'd like**
Upload citrix vda binary from local machine using google_storage_bucket_object in bootstrap

**Describe alternatives you've considered**
The solution proposed satisfies the current requirements

**Additional context**
N/A

**Comment by adamgft** [comment]
ticket moved to citrix board
