### ISSUE TITLE
Jenkins fails on startup

### ISSUE THREAD

**Issue by sunderhill-gft** [tranquilitybase-io/tb-gcp#492]
Jenkins is deployed as part of the Eagle Console Kubernetes Cluster

Currently, when Jenkins is deployed it fails to start and cannot be reached at the IP address http://10.0.1.10. The Jenkins log with errors is attached here - 
[jenkins_log.txt](https://github.com/tranquilitybase-io/tb-gcp/files/5311384/jenkins_log.txt)

This happens on all deployments of Tranquility Base,

**Comment by harris-agyeman** [comment]
new ip for jenkins-  http://10.0.1.9
this ticket can be closed now cheers

**Comment by sunderhill-gft** [comment]
No longer an issue
