### ISSUE TITLE
Ensure Jenkins/Mysql/Redis can survive a restart of the EC Kubernetes cluster

### ISSUE THREAD

**Issue by sunderhill-gft** [tranquilitybase-io/tb-gcp#493]
Ensure the Jenkins persistent disk is reattached after the EC Kubernetes cluster is completely restarted. i.e. the Node Pool node size is set to 0 and then back to 1.

The same applies to the disks for Mysql and Redis.

Things to look out for:
The zone that the disk is on compared to the rest of the cluster.
The ReclaimPolicy of the storage classes/volume claims

**Comment by Salles-FA** [comment]
Hi @rjmco and @harris-agyeman,

I've just noticed the PR #512 is closed without merging. By solving this issue we'll get the ability to save costs by shutting down the cluster when it's not being used. 

Do you have any update?

**Comment by Salles-FA** [comment]
@sunderhill-gft @RDHA-GFT
