### ISSUE TITLE
Making Terraform Provider versions configurable instead of pulling adhoc latest version 

### ISSUE THREAD

**Issue by parmendra17** [tranquilitybase-io/tb-gcp#50]
This is a vector of instability as the latest provider versions are not necessarily always compatible with rest of the code state. Recently we have been having issues with Google provider versions. The quick fix was to change the version in respective files. We would need to make the providers versions configurable across all modules , so its transparent and does not require high touch to upgrade downgrade.

**Comment by sunderhill-gft** [comment]
It is not possible to set a provider version to a variable in Terraform.

**Comment by oscarmon7** [comment]
Terraform provider versions locked down as per #133
