### ISSUE TITLE
[Feature] Add 'dac user' to Jenkins so that DAC can monitor running jobs on Jenkins

### ISSUE THREAD

**Issue by sunderhill-gft** [tranquilitybase-io/tb-gcp#508]
Add 'dac user' (not an admin) to Jenkins so that DAC can monitor running jobs on Jenkins

Add DAC_JENKINS_USER / DAC_JENKINS_PASSWORD as environment variables to DAC Kubernetes configuration ensuring these are secret

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/tb-gcp-dac/issues/113
