### ISSUE TITLE
[DEBT] TB code on tf-server-<random> should preserve git history

### ISSUE THREAD

**Issue by rjmco** [tranquilitybase-io/tb-gcp#525]
**Is your feature request related to a problem? Please describe.**

Tranquility Base's code is currently copied without any version control information into the packer image. This hinders the ability to quickly compare and import improvements from the upstream project from the `tf-server-<random>` in long lasting Tranquility Base deployments.

**Describe the solution you'd like**
The image generated by packer should contain a clone of the git repository at the `HEAD` which the image is meant to deliver (e.g. `master` or `issue-*` heads).

**Describe alternatives you've considered**

Consider cloning a single branch to save on image space, but do so if there's an ability to *unshallow* the git clone as this [stackoverflow question/answers](https://stackoverflow.com/questions/1778088/how-do-i-clone-a-single-branch-in-git) alludes to.

**Additional context**

(none provided)

**Comment by Salles-FA** [comment]
Hi @rjmco ,

Have you considered using the tags instead of branches? e.g. 
```sh
git checkout v1.28.39
```

- https://github.com/tranquilitybase-io/tb-gcp/tags

**Comment by rjmco** [comment]
@Salles-FA your idea is a good one. We should eventually have a versioned release cycle. However for now, images are only generated for `master` and `issue-*` branches and once deployed the code with configuration is uploaded into Source Code Repositories as shown here:

https://github.com/tranquilitybase-io/tb-gcp/blob/7237503a03cc2fc98850ad51238c81b8c1dc52f2/tb-gcp-tr/landingZone/tb-welcome#L114-L128

As you can see through the code a new repository is initialized without the context of where that code was sourced from. Without this context it will be very difficult to evolve existing deployments and merge code from upstream. This struggle is what I want to avoid first before imposing a formal versioned lifecycle with proper upgrade paths.
