### ISSUE TITLE
Change URL eagle-console.tranquilitybase.internal to eagle-console.tranquilitybase-demo.io

### ISSUE THREAD

**Issue by sunderhill-gft** [tranquilitybase-io/tb-gcp#532]
eagle-console.tranquilitybase.internal is used as a default for multiple variables in the terraform for landing zone deployment. This is causing problems in accessing the Eagle Console.
Replace with eagle-console.tranquilitybase-demo.io

**Comment by Salles-FA** [comment]
@harris-agyeman @RDHA-GFT,

Could you add the **Linked pull request**?

**Comment by harris-agyeman** [comment]
https://github.com/tranquilitybase-io/tb-gcp/pull/533 @Salles-FA
