### ISSUE TITLE
[ISSUE] Create tagged jenkins container image when a pull request is merged into master 

### ISSUE THREAD

**Issue by sunderhill-gft** [tranquilitybase-io/tb-gcp#543]
Create a container image for the jenkins server  in project tranquility-base-images on merging a pull request into master.

* Add cloudbuild.yaml to root of tb-jenkins project. Build file should build the docker container for jenkins. See example in tb-gcp-dac project
* Add versioning to tb-jenkins. Implement the semver.yml github task. See example in tb-gcp-dac project. This will add a version git tag to the code when a PR is merged into master. 
* Add cloud build trigger on tb-jenkins repo in project tranquility-base-images to build the container when a new git tag is detected.

**Comment by RDHA-GFT** [comment]
Completed
