### ISSUE TITLE
[BUG] Eagle Console Kubernetes Cluster does not start correctly with latest Landing Zone release

### ISSUE THREAD

**Issue by sunderhill-gft** [tranquilitybase-io/tb-gcp#584]
The Eagle Console Kubernetes services do not start up correctly after deploying the Landing Zone.
None of the pods for eagle-console, houston-service, gcp-dac or the mysql databases can be provisioned.

This is high priority as the Eagle Console is not useable now after a Landing Zone deployment.

**Comment by Waterhouse-GFT** [comment]
Solved by rollback
