### ISSUE TITLE
Investigate suitability of Prisma's Public Cloud IaC Scan API

### ISSUE THREAD

**Issue by scottholmangft** [tranquilitybase-io/tb-gcp#61]
Prisma's (Palo Alto/Redlock) Public Cloud IaC Scan API can scan CloudFormation, Terraform, Kubernetes deployment YAML files for security issues. Determine whether this can be used within TB

https://iacscanapidoc.redlock.io/

**Comment by RDHA-GFT** [comment]
Look at the potential to be an optional service activator
Public version of  https://iacscanapidoc.redlock.io/  no longer exists as has been bought by Palo so will need to look at other options or at Prisma as a paid option.
