### ISSUE TITLE
[BUG] tb-projects-deleter does not remove all resources deployed by TB.

### ISSUE THREAD

**Issue by Waterhouse-GFT** [tranquilitybase-io/tb-gcp#625]
**Describe the bug**

The manual TB delete script "tb-projects-deleter" does not remove all of the resources deployed by a TB deployment.

**To Reproduce**
1. Deploy TB
2. Run the delete script
3. Check the billing account SA binding.

**Expected behavior**

Delete script should remove all liens and SA's deployed by TB.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

See also : https://github.com/tranquilitybase-io/tb-gcp/issues/390

**Comment by geoff-gft** [comment]
brought into the wider delete script work
