### ISSUE TITLE
Sandbox project activator

### ISSUE THREAD

**Issue by scottholmangft** [tranquilitybase-io/tb-gcp#63]
Create Terraform sandbox activator to deploy an empty project. 

Reuse the project create code used for the GKE activator to create this sandbox project activator. 

This ought to be a module rather than being replicated across all activator code.

Integrate this activator with the Eagle Console (self-service portal).

Base Activator can be found here - https://github.com/tranquilitybase-io/tb-activator-gft-base

Needs the ability for an Admin to disable/enable APIs via the Eagle Console and to "save as" those settings as an Activator type.

Currently, when the Eagle Console deploys a [Solution](https://github.com/tranquilitybase-io/tb-gcp-dac/wiki/DaC-Solution-Service), it creates a number of empty Projects. But all APIs are enabled by default.

**Comment by oscarmon7** [comment]
Dev pushed to  branch _issue-63-sandbox_. Testing could not progress because:
1. appengine was not working
2. manual testing involved setting to many variables

**Comment by andy12838729** [comment]
This is almost the same as the https://github.com/tranquilitybase-io/tb-activator-gft-base repo

**Comment by Salles-FA** [comment]
On solution deployment, all APIs must be disabled for projects. They are only enabled when an Activator is deployed, and only the APIs the Activator needs.
- https://github.com/tranquilitybase-io/tb-gcp-dac/issues/52

**Comment by RDHA-GFT** [comment]
Has been dealt with under https://github.com/tranquilitybase-io/tb-eagle-console/issues/321
