### ISSUE TITLE
Update README.md with issues reference

### ISSUE THREAD

**Issue by scottholmangft** [tranquilitybase-io/tb-gcp#64]
Update the main readme.md with request for contributors to review the list of issues, and contribute.

**Comment by scottholmangft** [comment]
Updated README, committed, and submitted PR.

**Comment by oscarmon7** [comment]
Hi @scottholmangft , is this done?

**Comment by scottholmangft** [comment]
I can't remember why I opened this ticket. Documentation is being managed separately. Closing
