### ISSUE TITLE
[EPIC] Implement the necessary changes to the current  eagle console yaml to integrate it into the new TB management plane

### ISSUE THREAD

**Issue by adamgft** [tranquilitybase-io/tb-gcp#673]
**EPIC**
Based on the changes identified within the following tickets: 
https://github.com/tranquilitybase-io/tf-gcp-gke-config-module/issues/15
https://github.com/tranquilitybase-io/tf-gcp-gke-config-module/issues/16
https://github.com/tranquilitybase-io/tf-gcp-gke-config-module/issues/17
https://github.com/tranquilitybase-io/tf-gcp-gke-config-module/issues/18

As an infrastructure automation engineer, I can take the 'manual'/bash script, which creates the EC services, config maps, gateways etc... and porting those over to terraform for use in a production environment
mainly this includes the 3 yaml files, jenkins, eagle-console and the gateway

N.B the password injection mechanism should not be part of this ticket but the work should use the implementation provided by https://github.com/tranquilitybase-io/tf-gcp-gke-config-module/issues/10

A/C:
the management plane will install all the services on GKE, with green pods, such as the DaC, Houston, Eagle console, jenkins, redis.

**Comment by RDHA-GFT** [comment]
Issue needs to be split into smaller tasks.
Currently
1 - istio install
2 - fw rules for istio
6 - dns 

Have been implemented but not fully tested as EC is not accessible after deployment.
The remaining steps:
3 - Private ingress
4 - istio services
5 - Manual build of pods and services
8 - EC configuration

These still need to be implemented and tested. 
7 - Certificate install has been worked on under ticket https://github.com/tranquilitybase-io/tb-gcp-management-plane-architecture/issues/36 but has not been tested yet.

**Comment by adamgft** [comment]
Been superseded by following tickets:

https://github.com/tranquilitybase-io/tf-gcp-gke-config-module/issues/15
https://github.com/tranquilitybase-io/tf-gcp-gke-config-module/issues/16
https://github.com/tranquilitybase-io/tf-gcp-gke-config-module/issues/18
https://github.com/tranquilitybase-io/tf-gcp-gke-config-module/issues/19
https://github.com/tranquilitybase-io/tb-gcp/issues/517
https://github.com/tranquilitybase-io/tf-gcp-gke-config-module/issues/17
