### ISSUE TITLE
Make all GKE clusters fully private

### ISSUE THREAD

**Issue by scottholmangft** [tranquilitybase-io/tb-gcp#78]
Currently all GKE clusters have public endpoints for the control plane. The nodes use private IPs, and master authorised networks are used to limited control plane access from the 10.0.0.0/8 CIDR; however, the control plane must be made private to further reduce the attack surface. This means gully private GKE clusters fully. 

All cluster management will be through a Linux bastion hosted by the remote access project, and accessible via IAP.

The main issue that has prevented the use of fully private GKE clusters is the need to access the Vault, iTop, and SSP projects during the bootstrap process to enable deployment of software using Helm. The boostrap process builds the Landing Zone from the Terraform Admin Server in the bootstrap project that is is not connected to the Shared VPC. This means that the Terraform server is not able to communicate over private IPs controlled by the Sahred VPC, so has to hit the public endpoint of the GKE clusters to deploy services.

There are a few possible solutions that need to be investigated:

Option 1: Create a temporary peering between the bootstrap project, and the shared VPC - might not work as the GKE control plane is located in a Google managed VPC that is already peered to the Shared VPC, and transitive peering is still not available. i.e. network A and network B are peered with network C. Both can communicate with network C but not with each other. 
Option 2: Create temporary VPN between bootstrap project, and Shared VPC - probably more viable than option 1
Option 3: Connect to the bastion host through IAP, and execute commands on the bastion host.

**EDIT: There is a fourth option. this is to deploy a Squid reserve proxy to tunnel kubectl and helm command to the GKE control plane. This solution has already been proven on another project. We'll reuse the code from the project.**

**Comment by stuartrl07** [comment]
Work has already been done on the HSBC GMB project, code located: https://github.com/tranquilitybase-gft/tb-gcp

**Comment by stuartrl07** [comment]
Current Progress:
Documentation of design: https://confluence.gft.com/pages/viewpage.action?spaceKey=MODAPPS&title=GCP+LZ#GCPLZ-LandingZoneGKESoftwareDeploymentviaSquidProxy(WIP)

Privoxy/Squid installed on an instance in the shared bastion project, new service account tied to it. Able to run kubectl commands and view the kubernetes clusters in other shared projects.

Able to ssh into this instance from tf-server in bootstrap, but need to enable port forwading to the proxy instance.

Need to make clusters private and create via proxy instead of public endpoints still.

**Comment by stuartrl07** [comment]
Current Status:
Final approach has been agreed:
Squid Proxy on instance inside shared bastion project, iap ssh tunnel created from tf-server to proxy, https_proxy value set to this proxy/port.
GKE cluster have private endpoint enabled and change authorised network from tf-server to the subnet in bastion project.
Then all kubectl/helm commands sent via the proxy.

The infrastructure has all been created for this task, and a new task raised for updating the commands and testing: https://github.com/tranquilitybase-io/tb-gcp/issues/258

**Comment by stuartrl07** [comment]
Update:

Changes Made
Infrastructure:
Compute Instance created in shared bastion project - startup script installs kubectl, squid and adds the iap as authorised ip address.
Proxy service account created in shared bastion project and attached to compute instance.
Enabled Container api on shared bastion project

Enabled private endpoint and nodes on gke clusters
Changed master authorised network from bastion nat ip to bastion subnet ip address.

Changed bastion project and instances to be created first after vpc creation.


Commands/Execution:
Created script to be run after infrastrucutre created, starts iap tunnel, sets https proxy to this proxy.
Modified kubectl commands to be output into a kube script to be run after
Script executed via the proxy after infrastructure created.
Https_proxy set, any infrastructure requiring this run after first deployment.

Issues/Solutions:
Nat gateway ip address reserved so cannot be connected to kube master network, meaning any terraform infrastructure relating to this now fails.
For example tiller_svc_account, if the https_proxy value is set to the bastion proxy these commands work but the rest of the commands do not.

The startup script on the proxy takes time to install packages. So the dependts on running via it are not working straight away and no way of making them wait.
Kubectl commands are sent to a script to be run after the terraform deployment when the iap-tunnel is fully running.

Too many local-execs throughout the code with no thought to order or dependencies.
These need to be looked at and modulised, if possible sent to scripts as local-execs should not be used this much.

Some infrastructure requires the proxy to work and others doesnt.
Retries attempted with the proxy value set if failed first time.
This needs to be looked at more and separated as cannot set a constant value and is hacky.


Need a meeting to finalise handover point and next steps.

**Comment by stuartrl07** [comment]
Modulised Kuberenetes cluster creation to have private cluster as input variable.
Set EC and ITSM clusters back to original non-private.
Created new Sec failover cluster and set to private for demonstration that it works

**Comment by stuartrl07** [comment]
Issue 78 – Private GKE Clusters
End Goal: Have the Eagle Console Cluster fully private, with the option to make other GKE clusters private. Vault removed as will be worked on separately, but functionality for making it private is there.

Changes made:
Bastion Project:
-	Enabled Containers API on shared-bastion project
-	New GCE instance for Squid Proxy.
-	New service account for proxy instance
-	New firewall rule for allowing IAP tunnel connection only
-	New startup script for Squid, downloads and allows IAP address range
-	IAP Tunnel command is output to a file to be run after infrastructure is created.
Kuberentes Cluster:
-	Private endpoint added as a variable when creating cluster.
-	Kubectl commands relating to Eagle Console output to file to be run when IAP-tunnel connection is up.
No/with-itop Main class:
-	Bastion project is created before kubernetes clusters now.
-	Eagle Console Cluster is created with private endpoint, and master ip range is moved from the bootstrap NAT IP to the Shared-bastion subnet to allow the proxy access.
-	Kubectl commands are moved to go into file to be repeated after infrastructure.

Tb-welcome script:
-	After the terraform apply has been executed, the iap tunnel is created and all the kube commands for private clusters are executed.
K8s Context:
-	Set to use internal ip of kuberentes cluster now as no external for EC.
Vault:
-	Vault cluster still created
-	Vault not installed as needs to be separated out into own activator like iTop
-	Vault output variable also removed from main script.


Issues and things needing work:
-	Vault needs to be refactored into own activator as is just part of the whole process for no reason as has no dependencies between anything else.
-	If running terraform provider for creating things on private GKE cluster it will need to be run through the proxy in the future. This is tricky as setting the proxy interrupts normal terraform infra, so need to look at how these can be split.
-	There are many local-exec commands throughout the code which needs to be looked at. These aren’t monitored by terraform and aren’t easy to enforce dependencies/order on even if they need order. So changes to one file can break the whole monolithic script approach. Either these should be executed after infrastructure has been created separate from Terraform, or use the terraform providers to run so it is managed properly.
-	For creating Kubernetes activator just need to manage what kubectl/helm commands are required and whether they require access to internal-ips or not, then can use iap-tunnel the same as has been done for eagle-console.
