### ISSUE TITLE
Eagle Console front-end portal  (aka Self Service Portal or SSP) for TranquilityBase

### ISSUE THREAD

**Issue by scottholmangft** [tranquilitybase-io/tb-gcp#79]
The Eagle Console (formerly The Self Service Portal) front-end code is only partially complete. The remaining pages comprising the provisioning of a solution space and the creation of applications through activators must be created. This issue only covers the development of the html and Angular code and back-end interaction will be supported by stubs. Wireframes for the process flow have been produced and are the main artifact to follow, these can be found here: [LINK]

**Comment by sandyasheri-gft** [comment]
- [ ] Create Side bar screen

- [ ] Create Login Screens

- [ ] Create Solution Dashboard
