### ISSUE TITLE
Secure Eagle Console (aka Self Service Portal or SSP) access 

### ISSUE THREAD

**Issue by scottholmangft** [tranquilitybase-io/tb-gcp#80]
Currently the Eagle Console is hosted by AppEngine, and therefore has a public IP; however, Eagle Console currently has no authentication, which means that anybody can connect to EC, and launch activators as many activators as they like.

Ideally Eagle Console needs to be containerised and hosted by the same GKE cluster as the backend. If not achievable by mid-Jan then IAP to provide a level of authentication/authorisation, and Cloud Armor must be deployed. IAP is more important then Cloud Armor.

**Comment by oscarmon7** [comment]
UI deployed in K8S already
