### ISSUE TITLE
SSP backend, Vault UI, and iTop UI need SSL/TLS

### ISSUE THREAD

**Issue by scottholmangft** [tranquilitybase-io/tb-gcp#81]
Currently communication between the SSP frontend and backend is unencrypted. The web UI of iTop and Vault use HTTP.

Find a solution to enforce HTTPS for all communication

**Comment by connor-mcshane** [comment]
https://istio.io/docs/tasks/traffic-management/ingress/secure-ingress/

**Comment by RDHA-GFT** [comment]
SSL has been implemented for Eagle Console. Vault and Itop optional activators will need to be re-written as optional shared services including access via HTTPs
