### ISSUE TITLE
iTop option to disable deployment

### ISSUE THREAD

**Issue by scottholmangft** [tranquilitybase-io/tb-gcp#82]
Due to the license used by iTop, and Google's Marketplace limitations on certain OSS licenses we must find a solution that enables us to deploy the LZ with iTop and without iTop

**Comment by dwalker1993** [comment]
Itop toggle incorporated in the code, now just to work through some errors. The default itop toggle will be in disable mode.

**Comment by oscarmon7** [comment]
Merged #116 into master.
