### ISSUE TITLE
CI/CD setup to package Tranquility Base image for Google Marketplace

### ISSUE THREAD

**Issue by sunderhill-gft** [tranquilitybase-io/tb-gcp#98]
**Packaging**
- Mirror Github repo to Google source repo
- Setup Google Cloud Build to package new Tranquility Base image whenever there is a Master branch checkin that passes tests. Use existing packer script to do this.
- Test image - see issue #112 
- Copy tagged image to Google Cloud Storage

**Comment by sunderhill-gft** [comment]
- Mirror Github repo to Google source repo
- Setup Google Cloud Build to package new Tranquility Base image whenever there is a Master branch checkin that passes tests.
- Store tagged image in Google Cloud Storage
- Run tests on created image

**Comment by oscarmon7** [comment]
Merged in PR#142
